import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Content-Type":"application/json"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const tg=()=>Deno.env.get("TELEGRAM_BOT_TOKEN")||"";
const api=()=>`https://api.telegram.org/bot${tg()}`;
async function telegram(method:string,body:Record<string,unknown>){const r=await fetch(`${api()}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json();}
function cleanJson(text:string){const t=text.trim().replace(/^```json/i,"").replace(/^```/i,"").replace(/```$/i,"").trim();try{return JSON.parse(t)}catch{}const a=t.indexOf("{");const b=t.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}return null;}
async function askAI(prompt:string){
  const dash=Deno.env.get("DASHSCOPE_API_KEY");
  const models=(Deno.env.get("DASHSCOPE_MODELS")||Deno.env.get("DASHSCOPE_MODEL")||"qwen3.7-flash,qwen-plus").split(",").map(x=>x.trim()).filter(Boolean);
  if(dash)for(const model of [...new Set(models)])try{const r=await fetch(`${(Deno.env.get("DASHSCOPE_BASE_URL")||"https://dashscope-intl.aliyuncs.com/compatible-mode/v1").replace(/\/+$/ ,"")}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${dash}`},body:JSON.stringify({model,temperature:.1,response_format:{type:"json_object"},messages:[{role:"system",content:"You are Agba, an operating business brain. Return only valid JSON."},{role:"user",content:prompt}]})});if(r.ok){const p=await r.json();const v=cleanJson(p?.choices?.[0]?.message?.content||"");if(v)return {value:v,provider:"alibaba",model:p?.model||model};}}catch{}
  const puter=Deno.env.get("PUTER_AUTH_TOKEN");
  if(puter)for(const model of [Deno.env.get("PUTER_MODEL")||"gpt-5.4-nano","gemini-3.1-flash-lite"])try{const r=await fetch(`${(Deno.env.get("PUTER_BASE_URL")||"https://api.puter.com/puterai/openai/v1").replace(/\/+$/ ,"")}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${puter}`},body:JSON.stringify({model,temperature:.1,messages:[{role:"system",content:"You are Agba. Return only valid JSON."},{role:"user",content:prompt}]})});if(r.ok){const p=await r.json();const c=p?.choices?.[0]?.message?.content;const v=typeof c==="string"?cleanJson(c):c;if(v)return {value:v,provider:"puter",model:p?.model||model};}}catch{}
  throw new Error("No AI provider returned valid output");
}
async function send(chat_id:number,text:string){const chunks=text.match(/[\s\S]{1,3800}/g)||[text];for(const chunk of chunks)await telegram("sendMessage",{chat_id,text:chunk});}
Deno.serve(async(req)=>{
  if(req.method!=="POST")return json({ok:true,service:"agba-telegram"});
  if(!tg())return json({error:"telegram_not_configured"},500);
  const secret=Deno.env.get("TELEGRAM_WEBHOOK_SECRET");if(secret&&req.headers.get("x-telegram-bot-api-secret-token")!==secret)return json({error:"forbidden"},403);
  let update:any;try{update=await req.json()}catch{return json({ok:true})}
  const msg=update?.message;if(!msg?.chat?.id)return json({ok:true});
  const chatId=Number(msg.chat.id);const text=String(msg.text||"").trim();
  const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{autoRefreshToken:false,persistSession:false}});
  const username=msg.from?.username||null;
  if(text==="/id"){await send(chatId,`Your Telegram chat ID is ${chatId}.`);return json({ok:true});}
  if(text==="/start"||text==="/help"){await send(chatId,"Agba 🧠\n\nI am your company operating brain.\n\n/connect <company-slug> <setup-secret>  Connect this chat.\n/id  Show your Telegram chat ID.\n/briefing  Get current business signals.\n\nAfter connecting, ask me business questions normally.");return json({ok:true});}
  const connect=text.match(/^\/connect\s+(\S+)\s+(\S+)$/i);
  if(connect){const setupSecret=Deno.env.get("TELEGRAM_CONNECT_SECRET");if(!setupSecret||connect[2]!==setupSecret){await send(chatId,"Connection rejected. The setup secret is invalid.");return json({ok:true});}const {data:org}=await supabase.from("agba_organizations").select("id,name,slug").eq("slug",connect[1]).maybeSingle();if(!org){await send(chatId,"I could not find that company slug.");return json({ok:true});}const {data:ceo}=await supabase.from("agba_users").select("id,organization_id,full_name,agba_roles!inner(code)").eq("organization_id",org.id).eq("active",true).eq("agba_roles.code","ceo").limit(1).maybeSingle();if(!ceo){await send(chatId,"That company does not have an active CEO user yet.");return json({ok:true});}await supabase.from("agba_telegram_bindings").upsert({chat_id:chatId,organization_id:org.id,agba_user_id:ceo.id,telegram_username:username});await send(chatId,`Connected to ${org.name}.\n\nYou can now ask Agba what needs attention, how cash is doing, what changed, or what actions are open.`);return json({ok:true});}
  const {data:binding}=await supabase.from("agba_telegram_bindings").select("organization_id,agba_user_id,agba_organizations(name,currency_code)").eq("chat_id",chatId).maybeSingle();
  if(!binding){await send(chatId,"This chat is not connected yet. Use /connect <company-slug> <setup-secret>.");return json({ok:true});}
  const orgId=binding.organization_id;
  if(text==="/briefing"){const {data:state}=await supabase.from("agba_state_items").select("title,summary,status,recommended_action,last_seen_at").eq("organization_id",orgId).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(12);const lines=(state||[]).map((s:any)=>`• ${s.title}: ${s.summary}${s.recommended_action?` Action: ${s.recommended_action}`:""}`);await send(chatId,lines.length?`Agba current state:\n\n${lines.join("\n")}`:"Agba has no active persistent business signals yet.");return json({ok:true});}
  if(!text)return json({ok:true});
  const [{data:state},{data:reports},{data:actions}]=await Promise.all([supabase.from("agba_state_items").select("title,summary,status,confidence,severity,recommended_action,last_seen_at").eq("organization_id",orgId).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(40),supabase.from("agba_reports").select("created_at,raw_text").eq("organization_id",orgId).order("created_at",{ascending:false}).limit(15),supabase.from("agba_actions").select("description,status,priority,owner_name,deadline").eq("organization_id",orgId).in("status",["open","in_progress"]).order("created_at",{ascending:false}).limit(20)]);
  const prompt=`Answer the CEO directly using only company evidence. Never invent facts. Question: ${text}\n\nPERSISTENT STATE:\n${JSON.stringify(state||[])}\n\nRECENT REPORTS:\n${JSON.stringify(reports||[])}\n\nOPEN ACTIONS:\n${JSON.stringify(actions||[])}\n\nReturn JSON: {"answer":"concise substantive answer","confidence":"high|medium|low","confidence_reason":"evidence reason","actions":[{"description":"specific action","owner_name":"name or null","deadline":"ISO timestamp or null","priority":"low|medium|high|critical"}]}`;
  try{const ai=await askAI(prompt);const v=ai.value||{};const answer=String(v.answer||v.response||v.summary||"I could not produce an answer from the available company evidence.");const confidence=["high","medium","low"].includes(String(v.confidence))?String(v.confidence):"medium";const reason=String(v.confidence_reason||"Based on available persistent state and recent reports.");const {data:q,error:qerr}=await supabase.from("agba_ceo_queries").insert({organization_id:orgId,asked_by:binding.agba_user_id,question:text,answer,confidence,confidence_reason:reason,provenance:{channel:"telegram",chat_id:chatId,state_count:(state||[]).length,report_count:(reports||[]).length,open_action_count:(actions||[]).length,provider:ai.provider,model:ai.model}}).select("id").single();if(qerr)throw qerr;const rows=Array.isArray(v.actions)?v.actions.map((a:any)=>({organization_id:orgId,created_by:binding.agba_user_id,description:String(a.description||a.action||"").trim(),owner_name:a.owner_name??null,deadline:a.deadline??null,status:"open",priority:["low","medium","high","critical"].includes(a.priority)?a.priority:"medium",source_ceo_query_id:q.id,metadata:{channel:"telegram"}})).filter((a:any)=>a.description):[];if(rows.length)await supabase.from("agba_actions").insert(rows);await send(chatId,`Agba 🧠\n\n${answer}\n\nConfidence: ${confidence}.`+(rows.length?`\n\nActions created: ${rows.length}.`:""));}catch(e){console.error(e);await send(chatId,"Agba could not answer that right now. Try again in a moment.");}
  return json({ok:true});
});
