import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Content-Type":"application/json"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:cors});
const tg=()=>Deno.env.get("TELEGRAM_BOT_TOKEN")||"";
const api=()=>`https://api.telegram.org/bot${tg()}`;
async function telegram(method:string,body:Record<string,unknown>){const r=await fetch(`${api()}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return r.json();}
function cleanJson(text:string){const t=text.trim().replace(/^```json/i,"").replace(/^```/i,"").replace(/```$/i,"").trim();try{return JSON.parse(t)}catch{}const a=t.indexOf("{");const b=t.lastIndexOf("}");if(a>=0&&b>a)try{return JSON.parse(t.slice(a,b+1))}catch{}return null;}
async function askAI(prompt:string){
 const dash=Deno.env.get("DASHSCOPE_API_KEY");
 const models=(Deno.env.get("DASHSCOPE_MODELS")||Deno.env.get("DASHSCOPE_MODEL")||"qwen3.7-flash,qwen-plus").split(",").map(x=>x.trim()).filter(Boolean);
 if(dash)for(const model of [...new Set(models)])try{const r=await fetch(`${(Deno.env.get("DASHSCOPE_BASE_URL")||"https://dashscope-intl.aliyuncs.com/compatible-mode/v1").replace(/\/+$/ ,"")}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${dash}`},body:JSON.stringify({model,temperature:.1,response_format:{type:"json_object"},messages:[{role:"system",content:"You are Agba, an operating business brain. Return only valid JSON."},{role:"user",content:prompt}]})});if(r.ok){const p=await r.json();const v=cleanJson(p?.choices?.[0]?.message?.content||"");if(v)return {value:v,provider:"alibaba",model:p?.model||model};}}catch{}
 const puter=Deno.env.get("PUTER_AUTH_TOKEN");
 if(puter)for(const model of [Deno.env.get("PUTER_MODEL")||"gpt-5.4-nano","gemini-3.1-flash-lite"])try{const r=await fetch(`${(Deno.env.get("PUTER_BASE_URL")||"https://api.puter.com/puterai/openai/v1").replace(/\/+$/ ,"")}/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${puter}`},body:JSON.stringify({model,temperature:.1,messages:[{role:"system",content:"You are Agba. Return only valid JSON."},{role:"user",content:prompt}]})});if(r.ok){const p=await r.json();const c=p?.choices?.[0]?.message?.content;const v=typeof c==="string"?cleanJson(c):c;if(v)return {value:v,provider:"puter",model:p?.model||model};}}catch{}
 throw new Error("No AI provider returned valid output");
}
async function send(chat_id:number,text:string,extra:Record<string,unknown>={}){const chunks=text.match(/[\s\S]{1,3800}/g)||[text];for(const chunk of chunks)await telegram("sendMessage",{chat_id,text:chunk,...extra});}
function bytesToHex(bytes:Uint8Array){return [...bytes].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function hashToken(token:string){return bytesToHex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token))));}
function randomToken(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function looksLikeReport(text:string){const t=text.toLowerCase();if(/^(daily|weekly|monthly)\s+(business\s+)?report\b/.test(t)||/^report\s*:/i.test(text))return true;const terms=["revenue","sales","orders","expenses","spent","customers","payments","overdue","delayed","tasks","supplier","inventory","profit","cash flow","staff","completed","outstanding"];return terms.filter(x=>t.includes(x)).length>=3;}
function roleLabel(role:string){return role==="ceo"?"company owner":role==="department_head"?"department head":"team member";}
Deno.serve(async(req)=>{
 if(req.method!=="POST")return json({ok:true,service:"agba-telegram"});
 if(!tg())return json({error:"telegram_not_configured"},500);
 const secret=Deno.env.get("TELEGRAM_WEBHOOK_SECRET");if(secret&&req.headers.get("x-telegram-bot-api-secret-token")!==secret)return json({error:"forbidden"},403);
 let update:any;try{update=await req.json()}catch{return json({ok:true})}
 const msg=update?.message;const cb=update?.callback_query;
 if(!msg?.chat?.id&&!cb?.message?.chat?.id)return json({ok:true});
 const chatId=Number(msg?.chat?.id||cb?.message?.chat?.id);const text=String(msg?.text||"").trim();
 const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{autoRefreshToken:false,persistSession:false}});
 const username=msg?.from?.username||cb?.from?.username||null;
 if(cb){
   const data=String(cb.data||"");
   if(data.startsWith("confirm_report:")){
     const reportId=data.slice("confirm_report:".length);
     const {data:binding}=await supabase.from("agba_telegram_bindings").select("organization_id,agba_user_id,role_code").eq("chat_id",chatId).maybeSingle();
     if(!binding||!['ceo','department_head'].includes(binding.role_code)){await telegram("answerCallbackQuery",{callback_query_id:cb.id,text:"Only the company owner or department head can confirm reports.",show_alert:true});return json({ok:true});}
     const {data:evidence}=await supabase.from("agba_business_evidence").select("id,status,submitted_by").eq("report_id",reportId).eq("organization_id",binding.organization_id).maybeSingle();
     if(!evidence){await telegram("answerCallbackQuery",{callback_query_id:cb.id,text:"I could not find that report.",show_alert:true});return json({ok:true});}
     if(evidence.submitted_by===binding.agba_user_id){await telegram("answerCallbackQuery",{callback_query_id:cb.id,text:"A report cannot be confirmed by the person who submitted it.",show_alert:true});return json({ok:true});}
     try{await supabase.rpc("confirm_agba_business_evidence",{p_evidence_id:evidence.id,p_member_id:binding.agba_user_id});await telegram("answerCallbackQuery",{callback_query_id:cb.id,text:"Report confirmed.",show_alert:false});await send(chatId,"Agba 🧠\n\nThat report is now confirmed and can be used as trusted business information.");}catch{await telegram("answerCallbackQuery",{callback_query_id:cb.id,text:"I could not confirm that report.",show_alert:true});}
   }
   return json({ok:true});
 }
 const startToken=text.match(/^\/start(?:\s+(.+))?$/i)?.[1]?.trim()||null;
 if(startToken){const tokenHash=await hashToken(startToken);const {data:invite}=await supabase.from("agba_telegram_invitations").select("id,organization_id,role_code,expires_at,used_at,agba_organizations(name)").eq("token_hash",tokenHash).maybeSingle();if(!invite){await send(chatId,"This invitation is not valid. Ask your company owner to generate a new invitation.");return json({ok:true});}if(invite.used_at||new Date(invite.expires_at).getTime()<Date.now()){await send(chatId,"This invitation has expired or has already been used. Ask your company owner for a new invitation.");return json({ok:true});}const {data:role}=await supabase.from("agba_roles").select("id").eq("code",invite.role_code).maybeSingle();if(!role){await send(chatId,"I could not complete the connection. Please ask your company owner to try again.");return json({ok:true});}const fullName=[msg?.from?.first_name,msg?.from?.last_name].filter(Boolean).join(" ")||username||`Telegram user ${chatId}`;const {data:user,error:userErr}=await supabase.from("agba_users").insert({organization_id:invite.organization_id,auth_user_id:crypto.randomUUID(),role_id:role.id,full_name:fullName,email:null,active:true}).select("id").single();if(userErr){console.error(userErr);await send(chatId,"I could not complete the connection. Please try again.");return json({ok:true});}const {error:bindErr}=await supabase.from("agba_telegram_bindings").upsert({chat_id:chatId,organization_id:invite.organization_id,agba_user_id:user.id,telegram_username:username,role_code:invite.role_code});if(bindErr){console.error(bindErr);await send(chatId,"I could not complete the connection. Please try again.");return json({ok:true});}await supabase.from("agba_telegram_invitations").update({used_at:new Date().toISOString(),used_chat_id:chatId}).eq("id",invite.id).is("used_at",null);await send(chatId,`Connected to ${(invite as any).agba_organizations?.name||"your company"}.\n\nYou are connected as a ${roleLabel(invite.role_code)}.\n\nYou can now talk to Agba normally.`);return json({ok:true});}
 if(text==="/id"){await send(chatId,`Your Telegram chat ID is ${chatId}.`);return json({ok:true});}
 if(text==="/start"||text==="/help"){await send(chatId,"Agba 🧠\n\nI'm your company's operating brain.\n\nI keep track of what is happening across your business and help you understand what needs attention.\n\nTo get started, ask your company owner for an Agba invitation.\n\nOnce connected, just talk to me normally.\n\nTry:\n• How is the business doing today?\n• What needs my attention?\n• What did we spend today?\n• Which tasks are overdue?\n\n/briefing\nGet today's business briefing.");return json({ok:true});}
 const {data:binding}=await supabase.from("agba_telegram_bindings").select("organization_id,agba_user_id,role_code,agba_organizations(name,currency_code)").eq("chat_id",chatId).maybeSingle();
 if(text==="/connect"){await send(chatId,binding?"This chat is already connected. Just talk to Agba normally.":"To connect this chat, ask your company owner to generate an Agba invitation, then tap the invitation link in Telegram.");return json({ok:true});}
 if(text==="/invite"||text.startsWith("/invite ")){if(!binding||binding.role_code!=="ceo"){await send(chatId,"Only the company owner can send Agba invitations.");return json({ok:true});}const requested=text.slice(7).trim().toLowerCase();const roleCode=requested==="manager"||requested==="department head"?"department_head":"department_head";const token=randomToken();const tokenHash=await hashToken(token);const expires=new Date(Date.now()+24*60*60*1000).toISOString();const {error}=await supabase.from("agba_telegram_invitations").insert({organization_id:binding.organization_id,created_by:binding.agba_user_id,token_hash:tokenHash,role_code:roleCode,expires_at:expires});if(error){console.error(error);await send(chatId,"I could not create the invitation right now. Please try again.");return json({ok:true});}const bot=Deno.env.get("TELEGRAM_BOT_USERNAME")||"agba_brain_bot";await send(chatId,`Your Agba invitation is ready.\n\nShare this link with your department head:\nhttps://t.me/${bot}?start=${token}\n\nThe invitation expires in 24 hours and can only be used once.`);return json({ok:true});}
 if(!binding){if(text)await send(chatId,"This chat is not connected yet. Ask your company owner for an Agba invitation.");return json({ok:true});}
 const orgId=binding.organization_id;
 if(text==="/briefing"){const {data:state}=await supabase.from("agba_state_items").select("title,summary,status,recommended_action,last_seen_at").eq("organization_id",orgId).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(12);const lines=(state||[]).map((s:any)=>`• ${s.title}: ${s.summary}${s.recommended_action?` Action: ${s.recommended_action}`:""}`);await send(chatId,lines.length?`Agba current state:\n\n${lines.join("\n")}`:"Agba has no active persistent business signals yet.");return json({ok:true});}
 if(!text)return json({ok:true});
 if(looksLikeReport(text)){const idempotencyKey=`telegram:${msg.message_id}`;const {data:existing}=await supabase.from("agba_reports").select("id").eq("organization_id",orgId).eq("idempotency_key",idempotencyKey).maybeSingle();if(existing){await send(chatId,"I already have that report.");return json({ok:true});}const confirmed=binding.role_code==="ceo";const {data:report,error}=await supabase.from("agba_reports").insert({organization_id:orgId,submitted_by:binding.agba_user_id,report_date:new Date().toISOString().slice(0,10),raw_text:text,source:"telegram",idempotency_key:idempotencyKey,status:"received",confirmation_status:confirmed?"confirmed":"pending",confirmed_by:confirmed?binding.agba_user_id:null,confirmed_at:confirmed?new Date().toISOString():null}).select("id").single();if(error){console.error(error);await send(chatId,"I received the report but could not save it right now. Please try again.");return json({ok:true});}const {error:evErr}=await supabase.from("agba_business_evidence").insert({organization_id:orgId,report_id:report.id,submitted_by:binding.agba_user_id,source_text:text,evidence_type:"report",status:confirmed?"confirmed":"pending",extracted_data:{channel:"telegram",telegram_chat_id:chatId,telegram_username:username},confirmed_by:confirmed?binding.agba_user_id:null,confirmed_at:confirmed?new Date().toISOString():null});if(evErr)console.error(evErr);if(confirmed){await send(chatId,"Report received and confirmed. I’ll use it as trusted business information.");}else{await send(chatId,"Report received.\n\nI’ve saved it for review. Before I treat it as confirmed business information, your company owner or department head needs to approve it.",{"reply_markup":{"inline_keyboard":[[{"text":"Confirm report","callback_data":`confirm_report:${report.id}`}]]}});}return json({ok:true});}
 const [{data:state},{data:reports},{data:actions}]=await Promise.all([supabase.from("agba_state_items").select("title,summary,status,confidence,severity,recommended_action,last_seen_at").eq("organization_id",orgId).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(40),supabase.from("agba_reports").select("created_at,raw_text,confirmation_status").eq("organization_id",orgId).eq("confirmation_status","confirmed").order("created_at",{ascending:false}).limit(15),supabase.from("agba_tasks").select("title,status,priority,assignee_name,due_at").eq("organization_id",orgId).in("status",["open","in_progress"]).order("created_at",{ascending:false}).limit(20)]);
 const prompt=`Answer the CEO directly using only confirmed company evidence. Never invent facts and do not use pending reports. Question: ${text}\n\nPERSISTENT STATE:\n${JSON.stringify(state||[])}\n\nRECENT CONFIRMED REPORTS:\n${JSON.stringify(reports||[])}\n\nOPEN TASKS:\n${JSON.stringify(actions||[])}\n\nReturn JSON: {"answer":"concise substantive answer","confidence":"high|medium|low","confidence_reason":"evidence reason","actions":[{"description":"specific action","owner_name":"name or null","deadline":"ISO timestamp or null","priority":"low|medium|high|critical"}]}`;
 try{const ai=await askAI(prompt);const v=ai.value||{};const answer=String(v.answer||v.response||v.summary||"I could not produce an answer from the available company evidence.");const confidence=["high","medium","low"].includes(String(v.confidence))?String(v.confidence):"medium";const reason=String(v.confidence_reason||"Based on confirmed company evidence.");const {data:q,error:qerr}=await supabase.from("agba_ceo_queries").insert({organization_id:orgId,asked_by:binding.agba_user_id,question:text,answer,confidence,confidence_reason:reason,provenance:{channel:"telegram",chat_id:chatId,state_count:(state||[]).length,report_count:(reports||[]).length,open_task_count:(actions||[]).length,provider:ai.provider,model:ai.model}}).select("id").single();if(qerr)throw qerr;const rows=Array.isArray(v.actions)?v.actions.map((a:any)=>({organization_id:orgId,created_by:binding.agba_user_id,title:String(a.description||a.action||"").trim(),assignee_name:a.owner_name??null,due_at:a.deadline??null,status:"open",priority:["low","medium","high","critical"].includes(a.priority)?a.priority:"medium",source_ceo_query_id:q.id,metadata:{channel:"telegram"}})).filter((a:any)=>a.title):[];if(rows.length)await supabase.from("agba_tasks").insert(rows);await send(chatId,`Agba 🧠\n\n${answer}`);}catch(e){console.error(e);await send(chatId,"Agba could not answer that right now. Try again in a moment.");}
 return json({ok:true});
});
