import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { createAction, updateActionStatus, assignAction, setActionDeadline, setActionPriority } from "../_shared/action-service.ts";

const H={"Content-Type":"application/json"};
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:H});
const env=(k:string)=>Deno.env.get(k)||"";
const norm=(s:string)=>s.toLowerCase().replace(/₦/g," naira ").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const STOP=new Set(["the","a","an","to","for","on","with","and","please","action","task","follow","up","mark","set","as","done","complete","completed","change","update","deadline","priority","make","it","my","open","actions","tomorrow","today"]);
function tokens(s:string){return new Set(norm(s).split(" ").filter(x=>x.length>2&&!STOP.has(x)));}
function sim(a:string,b:string){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/(A.size+B.size-n);}
function parseDate(value:string|null){if(!value)return null;const v=value.trim().toLowerCase();const now=new Date();const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);const y=Number(p.find(x=>x.type==="year")?.value),m=Number(p.find(x=>x.type==="month")?.value),d=Number(p.find(x=>x.type==="day")?.value);const base=new Date(Date.UTC(y,m-1,d,23,59,59));if(v==="today")return base.toISOString();if(v==="tomorrow"){base.setUTCDate(base.getUTCDate()+1);return base.toISOString();}if(v==="next week"){base.setUTCDate(base.getUTCDate()+7);return base.toISOString();}const weekdays:any={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6};if(weekdays[v]!==undefined){const delta=(weekdays[v]-base.getUTCDay()+7)%7||7;base.setUTCDate(base.getUTCDate()+delta);return base.toISOString();}const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString();}
function parseCreate(text:string){const re=/^(?:please\s+)?(?:create|add|make|set up|set)\s+(?:a|an)\s+(?:management\s+)?(?:action|task|request)\b/i;if(!re.test(text.trim()))return null;let body=text.trim().replace(re,"").trim(),due:string|null=null,owner:string|null=null,priority:"low"|"medium"|"high"="medium";let m=body.match(/\s*(?:,\s*)?(?:due|deadline)\s+(today|tomorrow|next week|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{4}-\d{2}-\d{2})\s*[.!]?$/i);if(m){due=m[1];body=body.slice(0,m.index).trim().replace(/[.,;]+$/g,"");}m=body.match(/\s+(?:and\s+)?(?:assign(?:\s+it)?\s+to|for)\s+([^,.;]+?)(?=\s+(?:to\s+)?(?:follow|check|call|review|handle|complete|resolve|contact|send|prepare|update|collect)\b|\s+and\s+(?:make|set)\s+(?:it\s+)?(?:high|medium|low)\b|$)/i);if(m){owner=m[1].trim();body=body.slice(0,m.index).trim().replace(/[.,;]+$/g,"")+body.slice((m.index||0)+m[0].length).trim();}if(!owner){m=body.match(/^([^,.;]+?)\s+to\s+(?=follow|check|call|review|handle|complete|resolve|contact|send|prepare|update|collect)\b/i);if(m){owner=m[1].trim();body=body.slice(m[0].length).trim();}}m=body.match(/\s+(?:and\s+)?(?:make|set)(?:\s+it)?\s+(high|medium|low)\s+(?:priority)?\s*[.!]?$/i);if(m){priority=m[1].toLowerCase() as any;body=body.slice(0,m.index).trim().replace(/[.,;]+$/g,"");}if(!due){m=body.match(/\s+(?:due|deadline)\s+(today|tomorrow|next week|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{4}-\d{2}-\d{2})\s*$/i);if(m){due=m[1];body=body.slice(0,m.index).trim().replace(/[.,;]+$/g,"");}}if(!owner){m=body.match(/\s+(?:and\s+)?assign(?:\s+it)?\s+to\s+([^,.;]+)\s*$/i);if(m){owner=m[1].trim();body=body.slice(0,m.index).trim().replace(/[.,;]+$/g,"");}}return body?{description:body,owner_name:owner,priority,deadline:parseDate(due)}:null;}
async function binding(sb:any,chat:number){const {data,error}=await sb.from("agba_telegram_bindings").select("organization_id,agba_user_id,role_code").eq("chat_id",chat).maybeSingle();if(error)throw error;return data;}
async function openActions(sb:any,org:string,owner?:string){let q=sb.from("agba_actions").select("id,description,status,priority,owner_name,deadline,created_at").eq("organization_id",org).in("status",["open","in_progress"]).order("created_at",{ascending:true}).limit(100);if(owner)q=q.ilike("owner_name",owner);const {data,error}=await q;if(error)throw error;return data||[];}
async function resolve(sb:any,org:string,needle:string){const rows=await openActions(sb,org),n=norm(needle);const exact=rows.find((a:any)=>norm(a.description)===n);if(exact)return {action:exact,ambiguous:false};const contains=rows.filter((a:any)=>{const d=norm(a.description);return d.includes(n)||n.includes(d);});if(contains.length===1)return {action:contains[0],ambiguous:false};const ranked=rows.map((a:any)=>({a,s:sim(needle,a.description)})).sort((x:any,y:any)=>y.s-x.s);if(ranked[0]&&ranked[0].s>=.30&&(!ranked[1]||ranked[0].s-ranked[1].s>=.10))return {action:ranked[0].a,ambiguous:false};return {action:null,ambiguous:ranked.some((x:any)=>x.s>=.20),candidates:ranked.filter((x:any)=>x.s>=.20).slice(0,3).map((x:any)=>x.a)};}
async function enqueue(sb:any,chat:number,org:string,inbox:string,text:string){const {error}=await sb.from("agba_telegram_delivery_outbox").insert({organization_id:org,inbox_id:inbox,chat_id:String(chat),payload:{chat_id:chat,text},status:"pending",attempts:0,max_attempts:5,next_attempt_at:new Date().toISOString()});if(error&&error.code!=="23505")throw error;}
async function handle(sb:any,update:any,inbox:string){const msg=update?.message;if(!msg?.chat?.id||!msg?.text)return false;const chat=Number(msg.chat.id),text=String(msg.text).trim(),b=await binding(sb,chat);if(!b)return false;const org=String(b.organization_id);const create=parseCreate(text);if(create){const rows=await openActions(sb,org);const dup=rows.find((a:any)=>norm(a.description)===norm(create.description)&&String(a.owner_name||"").toLowerCase()===String(create.owner_name||"").toLowerCase());if(dup){await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nThat action already exists: **${dup.description}**.`);return true;}const data=await createAction(sb,{organizationId:org,actorId:b.agba_user_id,description:create.description,ownerName:create.owner_name,deadline:create.deadline,priority:create.priority,metadata:{channel:"telegram",chat_id:chat,created_from:"telegram-user-request"}});await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nAction created: **${data.description}**.${data.owner_name?` Assigned to **${data.owner_name}**.`:""} Priority: **${data.priority}**.${data.deadline?` Due: **${new Date(data.deadline).toLocaleDateString("en-NG")}**.`:""}`);return true;}
if(/^\/?actions$/i.test(text)||/^(what does|show|list)\s+(my\s+)?(?:open\s+)?actions\??$/i.test(text)){const rows=await openActions(sb,org);const answer=rows.length?`Agba 🧠\n\n**Open management actions**\n\n${rows.map((a:any,i:number)=>`${i+1}. ${a.description} · ${a.priority}${a.owner_name?` · ${a.owner_name}`:" · unassigned"}${a.deadline?` · due ${new Date(a.deadline).toLocaleDateString("en-NG")`:""}`).join("\n")}`:`Agba 🧠\n\nYou currently have no open management actions.`;await enqueue(sb,chat,org,inbox,answer);return true;}
const who=text.match(/^(?:what does|what has|show me)\s+(.+?)\s+(?:have|has)\s+open\??$/i);if(who){const rows=await openActions(sb,org,who[1].trim());const answer=rows.length?`Agba 🧠\n\n${who[1].trim()} currently has ${rows.length} open action${rows.length===1?"":"s"}:\n${rows.map((a:any)=>`• ${a.description} · ${a.priority}${a.deadline?` · due ${new Date(a.deadline).toLocaleDateString("en-NG")`:""}`).join("\n")}`:`Agba 🧠\n\n${who[1].trim()} has no open actions.`;await enqueue(sb,chat,org,inbox,answer);return true;}
const done=text.match(/^(?:mark|set)\s+(.+?)\s+(?:as\s+)?(?:done|complete|completed)$/i)||text.match(/^complete\s+(.+)$/i);if(done){const r=await resolve(sb,org,done[1]);if(r.ambiguous){await enqueue(sb,chat,org,inbox,"Agba 🧠\n\nI found more than one possible action. Please specify which one you mean.");return true;}if(!r.action){await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nI couldn't find an open management action matching \"${done[1]}\".`);return true;}const data=await updateActionStatus(sb,{organizationId:org,actorId:b.agba_user_id,actionId:r.action.id,status:"done",metadata:{completed_via:"telegram",completed_at:new Date().toISOString()}});await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nDone. **${data.description}** is now marked complete.`);return true;}
const upd=text.match(/^(?:change|update|set)\s+(?:the\s+)?(.+?)\s+(?:deadline|due date)\s+to\s+(today|tomorrow|next week|monday|tuesday|wednesday|thursday|friday|saturday|sunday|\d{4}-\d{2}-\d{2})\.?$/i);if(upd){const r=await resolve(sb,org,upd[1]);if(r.ambiguous){await enqueue(sb,chat,org,inbox,"Agba 🧠\n\nI found multiple matching actions. Please specify which action you want to update.");return true;}if(!r.action){await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nI couldn't find an open action matching \"${upd[1]}\".`);return true;}const data=await setActionDeadline(sb,{organizationId:org,actorId:b.agba_user_id,actionId:r.action.id,deadline:parseDate(upd[2])});await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nUpdated **${data.description}**. Deadline: **${new Date(data.deadline).toLocaleDateString("en-NG")}**.`);return true;}
const pri=text.match(/^(?:change|update|set|make)\s+(?:the\s+)?(.+?)\s+(?:priority|priority level)\s+(?:to\s+)?(high|medium|low)\.?$/i)||text.match(/^(?:make|set)\s+(?:the\s+)?(.+?)\s+(?:a\s+)?(high|medium|low)\s+priority\.?$/i);if(pri){const r=await resolve(sb,org,pri[1]);if(r.ambiguous){await enqueue(sb,chat,org,inbox,"Agba 🧠\n\nI found multiple matching actions. Please specify which action you want to update.");return true;}if(!r.action){await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nI couldn't find an open action matching \"${pri[1]}\".`);return true;}const data=await setActionPriority(sb,{organizationId:org,actorId:b.agba_user_id,actionId:r.action.id,priority:pri[2].toLowerCase() as any});await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nUpdated **${data.description}**. Priority: **${data.priority}**.`);return true;}
const assign=text.match(/^(?:assign|reassign|give)\s+(.+?)\s+to\s+(.+)$/i);if(assign){const r=await resolve(sb,org,assign[1]);if(r.ambiguous){await enqueue(sb,chat,org,inbox,"Agba 🧠\n\nI found multiple matching actions. Please specify which action you want to reassign.");return true;}if(!r.action){await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nI couldn't find an open action matching \"${assign[1]}\".`);return true;}const data=await assignAction(sb,{organizationId:org,actorId:b.agba_user_id,actionId:r.action.id,ownerName:assign[2].trim()});await enqueue(sb,chat,org,inbox,`Agba 🧠\n\nUpdated **${data.description}**. Assigned to **${data.owner_name**}.`);return true;}
return false;}

Deno.serve(async(req)=>{if(req.method!=="POST")return json({ok:true,service:"agba-action-router"});const url=env("SUPABASE_URL"),key=env("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)return json({error:"not_configured"},500);const expected=env("TELEGRAM_WORKER_SECRET");if(expected&&req.headers.get("x-agba-worker-secret")!==expected)return json({error:"forbidden"},403);const sb=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});let update:any;try{update=await req.json()}catch{return json({ok:true})}const inbox=String(update?._agba_inbox_id||update?.message?.message_id||"");if(!inbox)return json({ok:false,error:"missing_inbox_id"},400);try{const handled=await handle(sb,update,inbox);if(handled)return json({ok:true,handled:true,chat_id:Number(update?.message?.chat?.id||0)});const gateway=`${url}/functions/v1/telegram-gateway`;const r=await fetch(gateway,{method:"POST",headers:{...H,"x-agba-worker-secret":req.headers.get("x-agba-worker-secret")||""},body:JSON.stringify(update)});const body=await r.text();if(!r.ok)throw Error(`gateway_failed:${body.slice(0,500)}`);return new Response(body,{status:r.status,headers:H});}catch(e){console.error("action_router_failed",e);return json({ok:false,error:e instanceof Error?e.message:String(e)},500);}});