const url=Deno.env.get("SUPABASE_URL")||"";
const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
if(!url||!key)throw new Error("Missing Supabase test environment");
const h={apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"};
async function rpc(name:string,body:any={}){const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:h,body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(`${name} ${r.status}: ${t}`);try{return JSON.parse(t)}catch{return t}}
async function rows(path:string){const r=await fetch(`${url}/rest/v1/${path}`,{headers:h});const t=await r.text();if(!r.ok)throw new Error(`${path} ${r.status}: ${t}`);return JSON.parse(t)}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${url}${path}`,{...init,headers:{...h,...(init.headers||{})}});const t=await r.text();if(!r.ok)throw new Error(`${init.method||"GET"} ${path} ${r.status}: ${t}`);return t?JSON.parse(t):null}
async function router(chat:number,secret:string,text:string,inbox:string){const r=await fetch(`${url}/functions/v1/action-router`,{method:"POST",headers:{"Content-Type":"application/json","x-agba-worker-secret":secret},body:JSON.stringify({dry_run:false,_agba_inbox_id:inbox,message:{chat:{id:chat},text,message_id:Date.now()}})});const t=await r.text();if(!r.ok)throw new Error(`router ${r.status}: ${t}`);return JSON.parse(t)}
function lagosTomorrow(){const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const d=new Date(Date.UTC(+p.find(x=>x.type==="year")!.value,+p.find(x=>x.type==="month")!.value-1,+p.find(x=>x.type==="day")!.value,23,59,59));d.setUTCDate(d.getUTCDate()+1);return d.toISOString()}
function lagosNextFriday(){const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const d=new Date(Date.UTC(+p.find(x=>x.type==="year")!.value,+p.find(x=>x.type==="month")!.value-1,+p.find(x=>x.type==="day")!.value,23,59,59));d.setUTCDate(d.getUTCDate()+((5-d.getUTCDay()+7)%7||7));return d.toISOString()}
function sameInstant(a:any,b:any){return !!a&&!!b&&new Date(a).getTime()===new Date(b).getTime()}
const secret=String(await rpc("agba_telegram_worker_secret"));
const bindings=await rows("agba_telegram_bindings?select=chat_id,organization_id,agba_user_id&limit=1");
if(!bindings.length)throw new Error("No Telegram binding fixture");
const chat=Number(bindings[0].chat_id),org=bindings[0].organization_id,marker=`WORKFORCE-E2E-${Date.now()}`;
let inboxId:string|undefined;let actionId:string|undefined;
try{
  const updateId=Number(`${Date.now()}${Math.floor(Math.random()*1000).toString().padStart(3,"0")}`);
  const inserted=await rest("/rest/v1/agba_telegram_update_inbox?select=id,status",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({telegram_update_id:updateId,payload:{message:{chat:{id:chat},text:`Create an action for Chinedu to follow up with supplier ${marker}, due tomorrow and make it high priority.`}},chat_id:chat,status:"processing",attempts:1,max_attempts:3,locked_at:new Date().toISOString(),next_attempt_at:new Date().toISOString()})});
  inboxId=inserted[0].id;
  console.log("WORKFORCE ACTION ROUTER E2E");
  const createText=`Create an action for Chinedu to follow up with supplier ${marker}, due tomorrow and make it high priority.`;
  const created=await router(chat,secret,createText,inboxId);if(!created.handled)throw new Error(`create not handled: ${JSON.stringify(created)}`);console.log("- create: PASS");
  let r=await rows(`agba_actions?organization_id=eq.${org}&description=like.*${encodeURIComponent(marker)}*&select=id,organization_id,description,status,priority,owner_name,deadline`);if(r.length!==1)throw new Error(`created action lookup mismatch: ${JSON.stringify(r)}`);let a=r[0];actionId=a.id;if(a.organization_id!==org||a.status!=="open"||a.owner_name!=="Chinedu"||a.priority!=="high"||!sameInstant(a.deadline,lagosTomorrow()))throw new Error(`create state mismatch: ${JSON.stringify(a)}`);console.log("- create persistence + owner + priority + deadline: PASS");
  let q=await router(chat,secret,`What does Chinedu have open?`,inboxId);if(!q.handled)throw new Error(`owner read failed: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&organization_id=eq.${org}&select=id,owner_name,status`);if(r.length!==1||r[0].owner_name!=="Chinedu"||!['open','in_progress'].includes(r[0].status))throw new Error(`owner read DB verification failed: ${JSON.stringify(r)}`);console.log("- owner read: PASS");
  q=await router(chat,secret,`Change the ${marker} deadline to Friday`,inboxId);if(!q.handled)throw new Error(`deadline update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&select=deadline`);if(!sameInstant(r[0]?.deadline,lagosNextFriday()))throw new Error(`deadline not persisted: ${JSON.stringify(r[0])}`);console.log("- deadline update + verification: PASS");
  q=await router(chat,secret,`Make the ${marker} high priority`,inboxId);if(!q.handled)throw new Error(`priority update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&select=priority`);if(r[0]?.priority!=="high")throw new Error(`priority not persisted: ${JSON.stringify(r[0])}`);console.log("- priority update + verification: PASS");
  q=await router(chat,secret,`Reassign the ${marker} to Chinedu`,inboxId);if(!q.handled)throw new Error(`assignment update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&select=owner_name`);if(r[0]?.owner_name!=="Chinedu")throw new Error(`owner not persisted: ${JSON.stringify(r[0])}`);console.log("- assignment update + verification: PASS");
  q=await router(chat,secret,`Mark the ${marker} as done`,inboxId);if(!q.handled)throw new Error(`completion not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&select=status`);if(r[0]?.status!=="done")throw new Error(`completion not persisted: ${JSON.stringify(r[0])}`);console.log("- complete + verification: PASS");
  q=await router(chat,secret,`Mark the ${marker} as done`,inboxId);if(!q.handled)throw new Error(`terminal repeat not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${actionId}&select=status,owner_name,priority,deadline`);if(r[0]?.status!=="done"||r[0]?.owner_name!=="Chinedu"||r[0]?.priority!=="high"||!sameInstant(r[0]?.deadline,lagosNextFriday()))throw new Error(`terminal repeat mutated completed action: ${JSON.stringify(r[0])}`);console.log("- terminal repeat protection: PASS");
  console.log("WORKFORCE ACTION ROUTER E2E: PASS");
}finally{
  await rest(`/rest/v1/agba_state_items?organization_id=eq.${org}&or=(title.ilike.*${encodeURIComponent(marker)}*,summary.ilike.*${encodeURIComponent(marker)}*,state_key.ilike.*${encodeURIComponent(marker)}*)`,{method:"DELETE"}).catch(e=>console.error("state cleanup failed",e));
  if(actionId)await rest(`/rest/v1/agba_actions?id=eq.${actionId}`,{method:"DELETE"}).catch(e=>console.error("action cleanup failed",e));
  if(inboxId){await rest(`/rest/v1/agba_telegram_delivery_outbox?inbox_id=eq.${inboxId}`,{method:"DELETE"}).catch(e=>console.error("delivery cleanup failed",e));await rest(`/rest/v1/agba_telegram_update_inbox?id=eq.${inboxId}`,{method:"DELETE"}).catch(e=>console.error("inbox cleanup failed",e));}
}
