const url=Deno.env.get("SUPABASE_URL")||"";
const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
if(!url||!key)throw new Error("Missing Supabase test environment");
const h={apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"};
async function rpc(name:string,body:any={}){const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:h,body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw new Error(`${name} ${r.status}: ${t}`);try{return JSON.parse(t)}catch{return t}}
async function rows(path:string){const r=await fetch(`${url}/rest/v1/${path}`,{headers:h});const t=await r.text();if(!r.ok)throw new Error(`${path} ${r.status}: ${t}`);return JSON.parse(t)}
async function router(chat:number,secret:string,text:string){const r=await fetch(`${url}/functions/v1/action-router`,{method:"POST",headers:{"Content-Type":"application/json","x-agba-worker-secret":secret},body:JSON.stringify({dry_run:true,__agba_inbox_id:"e2e",message:{chat:{id:chat},text,message_id:Date.now()}})});const t=await r.text();if(!r.ok)throw new Error(`router ${r.status}: ${t}`);return JSON.parse(t)}
function lagosTomorrow(){const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const d=new Date(Date.UTC(+p.find(x=>x.type==="year")!.value,+p.find(x=>x.type==="month")!.value-1,+p.find(x=>x.type==="day")!.value,23,59,59));d.setUTCDate(d.getUTCDate()+1);return d.toISOString()}
function lagosNextFriday(){const p=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Lagos",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const d=new Date(Date.UTC(+p.find(x=>x.type==="year")!.value,+p.find(x=>x.type==="month")!.value-1,+p.find(x=>x.type==="day")!.value,23,59,59));d.setUTCDate(d.getUTCDate()+((5-d.getUTCDay()+7)%7||7));return d.toISOString()}
const secret=String(await rpc("agba_telegram_worker_secret"));
const bindings=await rows("agba_telegram_bindings?select=chat_id,organization_id,agba_user_id&limit=1");
if(!bindings.length)throw new Error("No Telegram binding fixture");
const chat=Number(bindings[0].chat_id),org=bindings[0].organization_id,marker=`WORKFORCE-E2E-${Date.now()}`;
console.log("WORKFORCE ACTION ROUTER E2E");
const createText=`Create an action for Chinedu to follow up with supplier ${marker}, due tomorrow and make it high priority.`;
const created=await router(chat,secret,createText);if(!created.handled||!created.action_id)throw new Error(`create not handled: ${JSON.stringify(created)}`);console.log("- create: PASS");
const id=created.action_id;
let r=await rows(`agba_actions?id=eq.${id}&select=id,organization_id,description,status,priority,owner_name,deadline`);if(r.length!==1)throw new Error("created action missing");let a=r[0];if(a.organization_id!==org||a.status!=="open"||a.owner_name!=="Chinedu"||a.priority!=="high"||String(a.deadline)!==String(lagosTomorrow()))throw new Error(`create state mismatch: ${JSON.stringify(a)}`);console.log("- create persistence + owner + priority + deadline: PASS");
let q=await router(chat,secret,`Show me Chinedu's open actions`);if(!q.handled||!String(q.text).includes(marker))throw new Error(`owner read failed: ${JSON.stringify(q)}`);console.log("- owner read: PASS");
q=await router(chat,secret,`Change the ${marker} deadline to Friday`);if(!q.handled)throw new Error(`deadline update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${id}&select=deadline`);if(String(r[0]?.deadline)!==String(lagosNextFriday()))throw new Error(`deadline not persisted: ${JSON.stringify(r[0])}`);console.log("- deadline update + verification: PASS");
q=await router(chat,secret,`Make the ${marker} high priority`);if(!q.handled)throw new Error(`priority update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${id}&select=priority`);if(r[0]?.priority!=="high")throw new Error(`priority not persisted: ${JSON.stringify(r[0])}`);console.log("- priority update + verification: PASS");
q=await router(chat,secret,`Reassign the ${marker} to Chinedu`);if(!q.handled)throw new Error(`assignment update not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${id}&select=owner_name`);if(r[0]?.owner_name!=="Chinedu")throw new Error(`owner not persisted: ${JSON.stringify(r[0])}`);console.log("- assignment update + verification: PASS");
q=await router(chat,secret,`Mark the ${marker} as done`);if(!q.handled)throw new Error(`completion not handled: ${JSON.stringify(q)}`);r=await rows(`agba_actions?id=eq.${id}&select=status`);if(r[0]?.status!=="done")throw new Error(`completion not persisted: ${JSON.stringify(r[0])}`);console.log("- complete + verification: PASS");
q=await router(chat,secret,`Mark the ${marker} as done`);if(!q.handled||!String(q.text).includes("couldn't find"))throw new Error(`completed action should not be repeatable: ${JSON.stringify(q)}`);console.log("- terminal repeat protection: PASS");
console.log("WORKFORCE ACTION ROUTER E2E: PASS");