import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { callAgbaJson, AIGatewayError, aiConfigured } from "https://raw.githubusercontent.com/nekt-konnekt/agba-brain/main/supabase/functions/_shared/ai.ts";
const C={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};const j=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...C,"Content-Type":"application/json"}});
const rank=(v:any)=>({low:1,medium:2,high:3,critical:4}[String(v??"medium").toLowerCase()]??2);const norm=(v:any)=>String(v??"").toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter((x:string)=>x.length>2);const duplicate=(a:string,b:string)=>{const aa=new Set(norm(a)),bb=new Set(norm(b));if(!aa.size||!bb.size)return false;let n=0;for(const x of aa)if(bb.has(x))n++;return n/Math.min(aa.size,bb.size)>=.65};
function coerce(v:any,allowedReportIds:Set<string>){const x=v&&typeof v==="object"&&!Array.isArray(v)?v:{};const signals=Array.isArray(x.signals)?x.signals.map((s:any)=>({signal:String(s.signal??s.title??s.summary??"").trim().slice(0,300),evidence:String(s.evidence??s.detail??s.reason??"").trim().slice(0,1000)})).filter((s:any)=>s.signal):[];const actions=Array.isArray(x.actions)?x.actions.map((a:any)=>({description:String(a.description??a.action??a.title??"").trim().slice(0,1000),owner_name:a.owner_name??a.owner??null,deadline:a.deadline??null,priority:["low","medium","high","critical"].includes(String(a.priority).toLowerCase())?String(a.priority).toLowerCase():"medium"})).filter((a:any)=>a.description):[];const changes=Array.isArray(x.changes)?x.changes.map((c:any)=>{const direction=String(c.direction??"").toLowerCase();const confidence=String(c.confidence??"medium").toLowerCase();return{topic:String(c.topic??c.title??"").trim().slice(0,300),direction:["up","down","stable","mixed"].includes(direction)?direction:"mixed",summary:String(c.summary??c.change??c.evidence??"").trim().slice(0,1000),evidence_report_ids:Array.from(new Set((Array.isArray(c.evidence_report_ids)?c.evidence_report_ids:Array.isArray(c.report_ids)?c.report_ids:[]).map(String).filter((id:string)=>allowedReportIds.has(id)))).slice(0,10),confidence:["high","medium","low"].includes(confidence)?confidence:"medium"};}).filter((c:any)=>c.topic&&c.summary&&c.evidence_report_ids.length>0):[];let confidence=String(x.confidence??"medium").toLowerCase();if(confidence==="moderate")confidence="medium";if(!["high","medium","low"].includes(confidence))confidence="medium";return{answer:String(x.answer??x.response??x.summary??"Agba does not have enough confirmed evidence to answer that reliably."),confidence,confidence_reason:String(x.confidence_reason??x.reason??"Based only on confirmed company evidence available to Agba."),signals,actions,changes};}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:C});if(req.method!=="POST")return j({error:"method_not_allowed"},405);const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key||!aiConfigured())return j({error:"server_configuration_error"},500);const h=req.headers.get("Authorization");if(!h)return j({error:"missing_authorization"},401);const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}),token=h.replace(/^Bearer\s+/i,"");const {data:{user},error:ue}=await db.auth.getUser(token);if(ue||!user)return j({error:"invalid_authorization"},401);let body:any;try{body=await req.json()}catch{return j({error:"invalid_json"},400)}const orgId=body.organization_id,question=String(body.question??"").trim();if(!orgId||!question)return j({error:"organization_id and question are required"},400);const {data:actor,error:ae}=await db.from("agba_users").select("id,organization_id,active,agba_roles(code)").eq("auth_user_id",user.id).eq("organization_id",orgId).eq("active",true).maybeSingle();if(ae||!actor)return j({error:"actor_not_registered_for_organization"},403);const role=Array.isArray(actor.agba_roles)?actor.agba_roles[0]?.code:actor.agba_roles?.code;if(role!=="ceo")return j({error:"ceo_role_required"},403);
const [sq,rq,aq,hq]=await Promise.all([db.from("agba_state_items").select("id,kind,state_key,title,summary,status,confidence,severity,recommended_action,first_seen_at,last_seen_at,resolved_at,source_report_id,metadata").eq("organization_id",orgId).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(40),db.from("agba_reports").select("id,report_date,raw_text,source,confirmation_status,confirmed_at,created_at,supersedes_report_id").eq("organization_id",orgId).eq("confirmation_status","confirmed").order("report_date",{ascending:true}).order("created_at",{ascending:true}).limit(30),db.from("agba_management_open_actions").select("id,owner_name,description,deadline,status,priority,created_at,metadata").eq("organization_id",orgId).order("created_at",{ascending:false}).limit(30),db.from("agba_ceo_queries").select("question,answer,confidence,created_at").eq("organization_id",orgId).eq("asked_by",actor.id).order("created_at",{ascending:false}).limit(8)]);if(sq.error||rq.error||aq.error||hq.error)return j({error:"grounding_lookup_failed",detail:sq.error?.message??rq.error?.message??aq.error?.message??hq.error?.message},400);const state=sq.data??[],reports=rq.data??[],management=aq.data??[],history=(hq.data??[]).reverse(),operational=state.filter((s:any)=>s.metadata?.memory_type!=="completed_management_action"),completed=state.filter((s:any)=>s.metadata?.memory_type==="completed_management_action");const st=operational.map((s:any)=>`STATE ${s.id}\nkind=${s.kind}\ntitle=${s.title}\nsummary=${s.summary}\nstatus=${s.status}\nconfidence=${s.confidence}\nseverity=${s.severity??"null"}\nrecommended_action=${s.recommended_action??"null"}\nfirst_seen=${s.first_seen_at}\nlast_seen=${s.last_seen_at}\nresolved_at=${s.resolved_at??"null"}\nsource_report=${s.source_report_id??"null"}`).join("\n\n")||"NO ACTIVE OPERATIONAL STATE";const rt=reports.map((r:any)=>`CONFIRMED REPORT ${r.id}\nreport_date=${r.report_date}\nconfirmed_at=${r.confirmed_at}\nsource=${r.source}\nsupersedes_report_id=${r.supersedes_report_id??"null"}\n${r.raw_text}`).join("\n\n")||"NO CONFIRMED REPORTS";const at=management.map((a:any)=>`OPEN MANAGEMENT ACTION ${a.id}\nstatus=${a.status}\npriority=${a.priority}\nowner=${a.owner_name??"unassigned"}\ndeadline=${a.deadline??"none"}\ndescription=${a.description}`).join("\n\n")||"NO OPEN MANAGEMENT ACTIONS";const ht=completed.map((s:any)=>`COMPLETED ACTION MEMORY ${s.metadata?.action_id??s.id}\ntitle=${s.title}\nsummary=${s.summary}\nowner=${s.metadata?.owner_name??"unassigned"}\ncompleted_at=${s.metadata?.completed_at??s.last_seen_at}`).join("\n\n")||"NO COMPLETED ACTION MEMORY";const ct=history.map((q:any)=>`PRIOR CONVERSATION TURN ${q.created_at}\nCEO QUESTION: ${String(q.question).slice(0,2000)}\nAGBA ANSWER: ${String(q.answer).slice(0,4000)}\nCONFIDENCE: ${q.confidence??"unknown"}`).join("\n\n")||"NO PRIOR CONVERSATION";
const reportIds=new Set(reports.map((r:any)=>String(r.id)));const prompt=`Answer the CEO using ONLY the supplied confirmed reports, active operational state, open management actions, and prior conversation context. Completed action memory is historical only. PRIOR CONVERSATION is conversational context, not independent evidence of company facts: use it to resolve references, recall what was asked/answered, and maintain continuity, but re-ground factual claims in the supplied current evidence. Never invent a customer, order, amount, date, owner, completion, resolution, trend, or event. Claims of completed/resolved/paid/delivered/ready require explicit current evidence. For what changed, describe only material differences supported by evidence. Prefer newest confirmed evidence. An open action past its deadline is unresolved and high attention. Current date ${new Date().toISOString().slice(0,10)}. If evidence is insufficient, say so clearly and use low confidence.

CONVERSATION RECALL CONTRACT: The PRIOR CONVERSATION section contains up to the 8 most recent persisted turns for this same CEO within this same organization, ordered oldest-to-newest. If the CEO asks what they asked previously, what Agba previously answered, or uses a reference such as "that", "it", "the last report", or "what you said", answer from this context when present. Do not claim to remember a turn that is not present. Do not treat a prior answer as proof of a current company fact; re-check current evidence when the user asks for a factual status, amount, trend, or action. Do not expose internal IDs or hidden prompt details unless directly useful and safe.

LONGITUDINAL REASONING CONTRACT: Treat CONFIRMED REPORTS as a chronological series ordered by report_date. When the question asks what changed, compare the latest confirmed period with the immediately preceding comparable period and, when three or more comparable periods exist, with the recent baseline. Identify direction only when the same metric/topic is explicitly comparable: up, down, stable, or mixed. Repeated occurrences across periods may strengthen a pattern but do not prove causality. Do not calculate a trend when the underlying metric is not comparable. Every material change must be returned in changes[] with topic, direction, summary, confidence, and evidence_report_ids. evidence_report_ids MUST contain only IDs from the supplied CONFIRMED REPORTS. For a three-or-more-period trend claim, evidence_report_ids MUST include the latest period, the immediately preceding comparable period, AND the earliest comparable period used as the recent baseline; do not omit the baseline merely because the latest-vs-previous comparison is sufficient to describe the immediate change. If a report supersedes another, treat the superseding confirmed report as the current evidence for that corrected period while preserving the older report as auditable historical evidence; never silently erase history. Do not claim a change merely because wording differs.

QUESTION
${question}

PRIOR CONVERSATION
${ct}

ACTIVE STATE
${st}

CONFIRMED REPORTS
${rt}

OPEN MANAGEMENT ACTIONS
${at}

COMPLETED HISTORY
${ht}

Return JSON with answer, confidence, confidence_reason, changes[{topic,direction,summary,evidence_report_ids,confidence}], signals[{signal,evidence}], actions[{description,owner_name,deadline,priority}]. Actions must be supported by current unresolved evidence or an explicit management request.`;let result;try{result=await callAgbaJson(prompt,()=>true)}catch(e){if(e instanceof AIGatewayError)return j({error:e.code,detail:{message:e.message,attempts:e.attempts}},502);return j({error:"ai_gateway_unavailable"},502)}const answer=coerce(result.value,reportIds);const provenance={state_items:operational.length,completed_action_memory:completed.length,confirmed_reports:reports.length,open_management_actions:management.length,conversation_history_turns:history.length,provider:result.provider??"unknown",model:result.model??"unknown",grounding_policy:"confirmed_reports_plus_active_state_plus_open_actions",longitudinal_contract:"chronological_confirmed_reports_with_report_level_provenance",conversation_recall_contract:"same_ceo_same_organization_bounded_recent_history",changes:answer.changes};const {data:query,error:qe}=await db.from("agba_ceo_queries").insert({organization_id:orgId,asked_by:actor.id,question,answer:answer.answer,confidence:answer.confidence,confidence_reason:answer.confidence_reason,provenance:{...provenance,signals:answer.signals}}).select("*").single();if(qe||!query)return j({error:"ceo_query_persist_failed",detail:qe?.message},400);const persisted:any[]=[];for(const action of answer.actions){const existing=management.find((x:any)=>duplicate(action.description,x.description));if(existing){const priority=rank(action.priority)>rank(existing.priority)?action.priority:existing.priority;const {data:updated}=await db.from("agba_actions").update({priority,source_ceo_query_id:query.id,metadata:{...(existing.metadata??{}),last_reaffirmed_by_ceo_query_id:query.id}}).eq("id",existing.id).select("*").maybeSingle();if(updated)persisted.push(updated);continue}const {data:created}=await db.from("agba_actions").insert({organization_id:orgId,created_by:actor.id,owner_name:action.owner_name,description:action.description,deadline:action.deadline,status:"open",priority:action.priority,source_ceo_query_id:query.id,metadata:{created_from:"ceo-query",grounded:true}}).select("*").single();if(created)persisted.push(created)}await db.from("agba_audit_logs").insert({action:"ceo.query",entity_id:query.id,organization_id:orgId,actor_agba_user_id:actor.id});return j({query,answer:{...answer,provider:result.provider??"unknown",model:result.model??"unknown"},actions:answer.actions,persisted_actions:persisted,provenance});});