import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const headers={"Content-Type":"application/json"};
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers});
const supabaseUrl=()=>Deno.env.get("SUPABASE_URL")||"";
const serviceKey=()=>Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const MAX_ATTEMPTS=5;
async function heartbeat(sb:any,status="healthy",success=false,errorMessage?:string){await sb.from("agba_system_components").update({status,last_heartbeat_at:new Date().toISOString(),...(success?{last_success_at:new Date().toISOString()}:{}),...(errorMessage?{metadata:{last_error:errorMessage.slice(0,500)}}:{})}).eq("key","telegram-worker").then((r:any)=>{if(r.error)console.error("component_heartbeat_failed",r.error)}).catch((e:any)=>console.error("component_heartbeat_failed",e))}
async function workerSecret(sb:any){const{data,error}=await sb.rpc("agba_telegram_worker_secret");if(error)throw error;return String(data||"")}
const isProposalCommand=(update:any)=>{const t=String(update?.message?.text||"").trim();return /^\/?(?:proposals|approve|reject|defer)\b/i.test(t)};
const isWorkforceCommand=(update:any)=>{const t=String(update?.message?.text||"").trim();return /^(?:please\s+)?(?:create|add|make|set up|set|assign|reassign|give|mark|complete|change|update|list|show|what does|what has|what are|\/actions)\b/i.test(t)};
async function dispatch(update:any,secret:string,inboxId:string){
 const target=isProposalCommand(update)?"proposal-router":isWorkforceCommand(update)?"action-router":"telegram-gateway";
 const r=await fetch(`${supabaseUrl()}/functions/v1/${target}`,{method:"POST",headers:{...headers,...(secret?{"x-agba-worker-secret":secret}:{})},body:JSON.stringify({...update,_agba_inbox_id:inboxId})});
 const b=await r.text();if(!r.ok)throw new Error(`${target}_http_${r.status}:${b.slice(0,500)}`);return;
}
Deno.serve(async(req)=>{if(req.method!=="POST")return json({ok:true,service:"agba-telegram-worker"});if(!supabaseUrl()||!serviceKey())return json({error:"worker_not_configured"},500);const sb=createClient(supabaseUrl(),serviceKey(),{auth:{autoRefreshToken:false,persistSession:false}});await heartbeat(sb);let body:any={};try{body=await req.json()}catch{}const expected=await workerSecret(sb).catch(e=>{console.error("telegram_worker_secret_lookup_failed",e);return""});if(!expected||body?.secret!==expected)return json({error:"forbidden"},403);let claimed:any[]=[];try{const{data,error}=await sb.rpc("agba_claim_telegram_update",{p_worker_id:"telegram-worker",p_lease_seconds:120});if(error)throw error;claimed=data||[]}catch(error){console.error("telegram_worker_claim_failed",error);await heartbeat(sb,"warn",false,String(error));return json({error:"queue_claim_failed"},500)}const item=claimed[0];if(!item){await heartbeat(sb,"healthy",true);return json({ok:true,processed:0});}try{await dispatch(item.payload,expected,item.id);const{error}=await sb.from("agba_telegram_update_inbox").update({status:"dispatched",dispatched_at:new Date().toISOString(),completed_at:new Date().toISOString(),locked_at:null,last_error:null}).eq("id",item.id).eq("status","processing");if(error)throw error;await heartbeat(sb,"healthy",true);return json({ok:true,processed:1,update_id:item.telegram_update_id,attempts:item.attempts})}catch(error){const message=error instanceof Error?error.message:String(error);const finalFailure=Number(item.attempts||0)>=MAX_ATTEMPTS;const{error:updateError}=await sb.from("agba_telegram_update_inbox").update({status:finalFailure?"dead":"failed",locked_at:null,last_error:finalFailure?`max_attempts_exceeded:${MAX_ATTEMPTS};${message}`.slice(0,2000):message.slice(0,2000)}).eq("id",item.id).eq("status","processing");if(updateError)console.error("telegram_worker_failure_state_update_failed",updateError);console.error("telegram_worker_dispatch_failed",{updateId:item.telegram_update_id,attempts:item.attempts,deadLettered:finalFailure,message});await heartbeat(sb,"warn",false,message);return json({ok:false,processed:0,update_id:item.telegram_update_id,attempts:item.attempts,dead_lettered:finalFailure,error:message},500)}});
