import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
async function heartbeat(admin:any,status="healthy",success=false){await admin.from("agba_system_components").update({status,last_heartbeat_at:new Date().toISOString(),...(success?{last_success_at:new Date().toISOString()}: {})}).eq("key","office-read").then((r:any)=>{if(r.error)console.error("component_heartbeat_failed",r.error)}).catch((e:any)=>console.error("component_heartbeat_failed",e))}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders}); if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(!supabaseUrl||!serviceRoleKey)return json({error:"server_configuration_error"},500);
 const authHeader=req.headers.get("Authorization"); if(!authHeader)return json({error:"missing_authorization"},401); const admin=createClient(supabaseUrl,serviceRoleKey,{auth:{autoRefreshToken:false,persistSession:false}}); const token=authHeader.replace(/^Bearer\s+/i,""); const {data:{user},error:userError}=await admin.auth.getUser(token); if(userError||!user)return json({error:"invalid_authorization"},401);
 const {data:actor,error:actorError}=await admin.from("agba_users").select("id,organization_id,department_id,active,full_name,agba_roles(code)").eq("auth_user_id",user.id).eq("active",true).maybeSingle(); if(actorError||!actor)return json({error:"actor_not_registered"},403); const role=Array.isArray(actor.agba_roles)?actor.agba_roles[0]?.code:actor.agba_roles?.code; if(role!=="ceo")return json({error:"ceo_role_required"},403);
 await heartbeat(admin); const orgId=actor.organization_id,today=new Date().toISOString().slice(0,10);
 const memoryRes=await fetch(`${supabaseUrl}/functions/v1/executive-memory`,{method:"POST",headers:{Authorization:`Bearer ${serviceRoleKey}`,"Content-Type":"application/json"},body:JSON.stringify({organization_id:orgId,limit:40})});
 if(!memoryRes.ok){await heartbeat(admin,"warn",false);return json({error:"executive_memory_unavailable",detail:await memoryRes.text()},502)} const canonical=await memoryRes.json(); const es=canonical.executive_state??{};
 const [orgQ,departmentsQ,reportsQ,metricsQ,queriesQ,telegramQ,inboundQ,outboundQ]=await Promise.all([
  admin.from("agba_organizations").select("id,name,timezone,currency_code").eq("id",orgId).single(),
  admin.from("agba_departments").select("id,name,slug,active").eq("organization_id",orgId).eq("active",true).order("name"),
  admin.from("agba_reports").select("id,department_id,submitted_by,report_date,raw_text,status,source,confirmation_status,confirmed_at,created_at,processed_at").eq("organization_id",orgId).eq("confirmation_status","confirmed").order("created_at",{ascending:false}).limit(40),
  admin.from("agba_metrics").select("name,key,unit,value_numeric,value_text,measured_on").eq("organization_id",orgId).order("measured_on",{ascending:false}).limit(50),
  admin.from("agba_ceo_queries").select("id,question,answer,confidence,confidence_reason,provenance,created_at").eq("organization_id",orgId).order("created_at",{ascending:false}).limit(12),
  admin.from("agba_telegram_bindings").select("chat_id,telegram_username,role_code,created_at,updated_at").eq("organization_id",orgId).order("updated_at",{ascending:false}).limit(10),
  admin.from("agba_telegram_update_inbox").select("id,message_id,payload,status,received_at,dispatched_at,completed_at,last_error").eq("organization_id",orgId).order("received_at",{ascending:false}).limit(12),
  admin.from("agba_telegram_delivery_outbox").select("id,inbox_id,payload,status,sent_at,created_at,updated_at,last_error").eq("organization_id",orgId).order("created_at",{ascending:false}).limit(12)
 ]); for(const q of [orgQ,departmentsQ,reportsQ,metricsQ,queriesQ,telegramQ,inboundQ,outboundQ])if(q.error){await heartbeat(admin,"warn",false);return json({error:"office_read_failed",detail:q.error.message},400)}
 const departments=departmentsQ.data??[],reports=reportsQ.data??[],metrics=metricsQ.data??[],queries=queriesQ.data??[],telegramBindings=telegramQ.data??[],inbound=inboundQ.data??[],outbound=outboundQ.data??[];
 const todayReports=reports.filter((r:any)=>r.report_date===today),reportsByDept=new Set(todayReports.map((r:any)=>r.department_id).filter(Boolean)),health=departments.length?Math.round((reportsByDept.size/departments.length)*100):0;
 const metric=(keys:string[])=>metrics.find((m:any)=>keys.some(k=>String(m.key??m.name).toLowerCase().includes(k))); const revenue=metric(["revenue","sales"]),outstanding=metric(["outstanding","receivable","receivables","unpaid"]);
 const departmentPulse=departments.map((d:any)=>{const deptReports=todayReports.filter((r:any)=>r.department_id===d.id);const deptState=(es.unresolved??[]).filter((s:any)=>s.department_id===d.id);const risk=deptState.find((s:any)=>["high","critical"].includes(s.severity));return{id:d.id,name:d.name,health:risk?"warn":deptReports.length?"good":"missing",text:risk?.summary??(deptReports.length?`${deptReports.length} report${deptReports.length>1?"s":""} received today`:"No confirmed report received today")}});
 const telegramMessages=inbound.map((item:any)=>({direction:"inbound",text:item.payload?.message?.text??item.payload?.message?.caption??null,username:item.payload?.message?.from?.username??null,received_at:item.received_at,status:item.status,last_error:item.last_error})).filter((m:any)=>m.text).slice(0,8); const telegramReplies=outbound.map((item:any)=>({direction:"outbound",text:item.payload?.text??item.payload?.message?.text??null,sent_at:item.sent_at??item.updated_at??item.created_at,status:item.status,last_error:item.last_error})).filter((m:any)=>m.text).slice(0,8);
 await heartbeat(admin,"healthy",true);
 return json({organization:orgQ.data,today,reporting_health:health,metrics:{revenue:revenue?{value:revenue.value_numeric??revenue.value_text,unit:revenue.unit,measured_on:revenue.measured_on}:null,outstanding:outstanding?{value:outstanding.value_numeric??outstanding.value_text,unit:outstanding.unit,measured_on:outstanding.measured_on}:null},attention:(es.what_needs_attention??[]).map((s:any)=>({icon:"!",title:s.title,text:s.summary,badge:String(s.severity??"attention").toUpperCase(),tone:["critical","high"].includes(s.severity)?"danger":"warn",source_state_item_id:s.id})).slice(0,6),changes:(es.what_changed??[]).map((s:any)=>({icon:"↑",title:s.what_happened,text:s.what_it_means,source_state_item_id:s.state_id})).slice(0,8),departments:departmentPulse,decisions:(es.decisions??[]),actions:(es.actions??[]),outcomes:(es.outcomes??[]),state:(canonical.memory?.active_state??[]).filter((s:any)=>s.metadata?.memory_type!=="completed_management_action").map((s:any)=>({id:s.id,kind:s.kind,title:s.title,summary:s.summary,severity:s.severity,confidence:s.confidence,recommended_action:s.recommended_action,last_seen_at:s.last_seen_at})),reports:reports.slice(0,12),conversations:queries,telegram:{connected:telegramBindings.length>0,bindings:telegramBindings.map((b:any)=>({telegram_username:b.telegram_username,role_code:b.role_code,created_at:b.created_at,updated_at:b.updated_at})),recent_messages:[...telegramMessages,...telegramReplies].sort((a:any,b:any)=>new Date(b.received_at??b.sent_at).getTime()-new Date(a.received_at??a.sent_at).getTime()).slice(0,10)},executive_state:es,memory:canonical.memory,counts:canonical.counts,source_counts:{reports:reports.length,conversations:queries.length,active_state:canonical.counts?.active_state??0,open_actions:canonical.counts?.open_actions??0,telegram_inbound:inbound.length,telegram_outbound:outbound.length}});
});
