-- Proactive operating layer
--
-- Watchers detect durable business conditions. Proposals are intentionally
-- separate from actions: a proposal is advice until governed execution occurs.

create table if not exists public.agba_proactive_watchers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.agba_organizations(id) on delete cascade,
  key text not null,
  name text not null,
  description text,
  enabled boolean not null default true,
  interval_seconds integer not null default 300 check (interval_seconds between 30 and 86400),
  last_run_at timestamptz,
  next_run_at timestamptz,
  last_error text,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, key)
);

create table if not exists public.agba_proposals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.agba_organizations(id) on delete cascade,
  watcher_id uuid references public.agba_proactive_watchers(id) on delete set null,
  reasoning_item_id uuid references public.agba_reasoning_items(id) on delete set null,
  action_id uuid references public.agba_actions(id) on delete set null,
  approval_id uuid references public.agba_approvals(id) on delete set null,
  fingerprint text not null,
  kind text not null,
  title text not null,
  summary text not null,
  recommendation text,
  status text not null default 'proposed' check (status in ('proposed','approved','rejected','executed','skipped','expired')),
  priority integer not null default 3 check (priority between 1 and 5),
  metadata jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, fingerprint)
);

create index if not exists idx_agba_proactive_watchers_due
  on public.agba_proactive_watchers (enabled, next_run_at);

create index if not exists idx_agba_proposals_org_status
  on public.agba_proposals (organization_id, status, priority, created_at desc);

alter table public.agba_proactive_watchers enable row level security;
alter table public.agba_proposals enable row level security;

create policy "agba proactive watchers org access"
  on public.agba_proactive_watchers
  for all
  using (organization_id = agba_private.current_org_id())
  with check (organization_id = agba_private.current_org_id());

create policy "agba proposals org access"
  on public.agba_proposals
  for all
  using (organization_id = agba_private.current_org_id())
  with check (organization_id = agba_private.current_org_id());

comment on table public.agba_proactive_watchers is
  'Durable proactive watcher definitions for Agba executive operations.';

comment on table public.agba_proposals is
  'Durable proposals generated by proactive watchers; proposals are not actions until governed execution occurs.';
