import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const headers = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
type Row=Record<string,any>;
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers}); if(req.method!=="POST")return json({error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(!url||!serviceRoleKey)return json({error:"server_configuration_error"},500);
 const authHeader=req.headers.get("Authorization"); if(!authHeader)return json({error:"missing_authorization"},401);
 const admin=createClient(url,serviceRoleKey,{auth:{autoRefreshToken:false,persistSession:false}}); const token=authHeader.replace(/^Bearer\s+/i,""); const internal=token===serviceRoleKey;
 const {data:authData,error:authError}=internal?{data:{user:null},error:null}:await admin.auth.getUser(token); if(!internal&&(authError||!authData.user))return json({error:"invalid_authorization"},401);
 let body:{organization_id:string;department_id?:string|null;limit?:number}; try{body=await req.json()}catch{return json({error:"invalid_json"},400)} if(!body.organization_id)return json({error:"organization_id_required"},400);
 let actor:Row|null=null;
 if(internal)actor={id:null,department_id:body.department_id??null,active:true,agba_roles:{code:"ceo"}}; else {const {data,error}=await admin.from("agba_users").select("id, department_id, active, agba_roles(code)").eq("auth_user_id",authData.user!.id).eq("organization_id",body.organization_id).eq("active",true).maybeSingle();if(error||!data)return json({error:"actor_not_registered_for_organization"},403);actor=data;}
 const role=actor.agba_roles?.code;if(role!=="ceo"&&role!=="department_head")return json({error:"insufficient_role"},403);const departmentId=role==="department_head"?(body.department_id??actor.department_id):(body.department_id??null);if(role==="department_head"&&departmentId!==actor.department_id)return json({error:"department_scope_violation"},403);
 const limit=Math.min(Math.max(Number(body.limit??30),1),60);const scoped=<T extends Row>(rows:T[]|null)=>(rows??[]).filter(r=>role==="ceo"||r.department_id===departmentId||r.department_id==null);
 const [stateQ,actionsQ,decisionsQ,goalsQ,proposalsQ,reportsQ,executionsQ]=await Promise.all([
  admin.from("agba_state_items").select("id,department_id,state_key,kind,title,summary,status,confidence,severity,recommended_action,first_seen_at,last_seen_at,source_reasoning_item_id,source_report_id,metadata").eq("organization_id",body.organization_id).in("status",["active","monitoring"]).order("last_seen_at",{ascending:false}).limit(limit),
  admin.from("agba_actions").select("id,department_id,owner_name,description,deadline,status,priority,source_ceo_query_id,source_state_item_id,metadata,created_at,updated_at").eq("organization_id",body.organization_id).in("status",["open","pending","assigned","in_progress"]).order("updated_at",{ascending:false}).limit(limit),
  admin.from("agba_decisions").select("id,department_id,title,decision_text,status,decided_at,created_at,updated_at").eq("organization_id",body.organization_id).order("updated_at",{ascending:false}).limit(limit),
  admin.from("agba_goals").select("id,department_id,title,description,status,target_value,current_value,unit,starts_on,target_date,created_at,updated_at").eq("organization_id",body.organization_id).in("status",["planned","active","at_risk"]).order("target_date",{ascending:true,nullsFirst:false}).limit(limit),
  admin.from("agba_proposals").select("id,watcher_id,reasoning_item_id,action_id,approval_id,kind,title,summary,recommendation,status,priority,metadata,expires_at,created_at,updated_at").eq("organization_id",body.organization_id).in("status",["proposed","approved"]).order("priority",{ascending:true}).order("created_at",{ascending:false}).limit(limit),
  admin.from("agba_reports").select("id,department_id,submitted_by,report_date,raw_text,status,source,confirmation_status,confirmed_at,created_at,processed_at").eq("organization_id",body.organization_id).eq("confirmation_status","confirmed").order("created_at",{ascending:false}).limit(limit),
  admin.from("agba_action_executions").select("id,organization_id,action_id,status,output,error,metadata,started_at,completed_at,updated_at,outcome_status,outcome_summary,outcome_evidence,outcome_next_state,outcome_recorded_at").eq("organization_id",body.organization_id).order("completed_at",{ascending:false,nullsFirst:false}).limit(limit),
 ]);
 for(const q of [stateQ,actionsQ,decisionsQ,goalsQ,proposalsQ,reportsQ,executionsQ])if(q.error)return json({error:"memory_lookup_failed",detail:q.error.message},400);
 const state=scoped(stateQ.data),actions=scoped(actionsQ.data),decisions=scoped(decisionsQ.data),goals=scoped(goalsQ.data),reports=scoped(reportsQ.data),proposals=proposalsQ.data??[],executions=executionsQ.data??[];
 const now=Date.now(),overdueActions=actions.filter(a=>a.deadline&&new Date(a.deadline).getTime()<now),criticalRisks=state.filter(s=>["risk","issue"].includes(s.kind)&&["high","critical"].includes(s.severity)),atRiskGoals=goals.filter(g=>g.status==="at_risk");
 const actionById=new Map(actions.map(a=>[a.id,a]));
 const recentOutcomes=executions.filter(e=>e.outcome_status||e.status==="succeeded"||e.status==="failed").slice(0,20).map(e=>{const action=actionById.get(e.action_id);return{execution_id:e.id,action_id:e.action_id,action:action?.description??null,execution_status:e.status,outcome_status:e.outcome_status??(e.status==="failed"?"failed":"unverified"),outcome_summary:e.outcome_summary??null,outcome_evidence:e.outcome_evidence??[],next_state:e.outcome_next_state??null,recorded_at:e.outcome_recorded_at??e.completed_at,output:e.output??null,error:e.error??null}});
 const unresolved=state.map(s=>({id:s.id,title:s.title,summary:s.summary,severity:s.severity,recommended_action:s.recommended_action,status:s.status,last_seen_at:s.last_seen_at}));
 const transitions=state.map(s=>{const relatedAction=actions.find(a=>a.source_state_item_id===s.id);const relatedDecision=decisions.find(d=>relatedAction?.metadata?.decision_id===d.id||d.title===s.title);const outcome=relatedAction?recentOutcomes.find(o=>o.action_id===relatedAction.id):null;return{state_id:s.id,what_happened:s.summary||s.title,what_it_means:s.recommended_action?`${s.recommended_action}`:null,decision:relatedDecision?{id:relatedDecision.id,title:relatedDecision.title,text:relatedDecision.decision_text,status:relatedDecision.status,decided_at:relatedDecision.decided_at}:null,action:relatedAction?{id:relatedAction.id,description:relatedAction.description,owner_name:relatedAction.owner_name,status:relatedAction.status,deadline:relatedAction.deadline}:null,outcome,remains_unresolved:s.status==="active"||s.status==="monitoring",last_seen_at:s.last_seen_at}});
 return json({organization_id:body.organization_id,scope:role==="ceo"&&!departmentId?"company":"department",department_id:departmentId,generated_at:new Date().toISOString(),executive_state:{what_changed:transitions.slice(0,12),what_needs_attention:criticalRisks.slice(0,8).map(s=>({id:s.id,title:s.title,summary:s.summary,severity:s.severity,recommended_action:s.recommended_action})),recommendations:proposals.filter(p=>p.status==="proposed").slice(0,8),decisions:decisions.slice(0,12),actions:actions.slice(0,20),outcomes:recentOutcomes,unresolved,reporting:{confirmed_reports:reports.slice(0,20)},active_goals:goals,at_risk_goals:atRiskGoals,critical_risks:criticalRisks},memory:{active_state:state,open_actions:actions,overdue_actions:overdueActions,decisions,active_goals:goals,at_risk_goals:atRiskGoals,proposals,critical_risks:criticalRisks,recent_reports:reports,recent_outcomes:recentOutcomes},counts:{active_state:state.length,open_actions:actions.length,overdue_actions:overdueActions.length,decisions:decisions.length,active_goals:goals.length,at_risk_goals:atRiskGoals.length,proposals:proposals.length,critical_risks:criticalRisks.length,recent_outcomes:recentOutcomes.length,unresolved:unresolved.length}});
});
