const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let supabaseClient=null,session=null,organizationId=null,officeData=null;
const config={url:window.AGBA_SUPABASE_URL||localStorage.getItem('AGBA_SUPABASE_URL')||'',anon:window.AGBA_SUPABASE_ANON_KEY||localStorage.getItem('AGBA_SUPABASE_ANON_KEY')||''};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function money(v,unit='NGN'){if(v===null||v===undefined||v==='')return 'Not reported';const n=Number(v);if(!Number.isNaN(n))return new Intl.NumberFormat('en-NG',{style:'currency',currency:unit==='NGN'?'NGN':unit,maximumFractionDigits:0}).format(n);return esc(v);}
function formatDate(v){if(!v)return 'No date';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('en-NG',{month:'short',day:'numeric',year:'numeric'});}
function renderList(id,items){const el=$(id);if(!el)return;el.innerHTML=items.length?items.map(x=>`<div class="item"><div class="item-icon">${esc(x.icon||'•')}</div><div style="flex:1"><div style="display:flex;gap:7px;align-items:center;justify-content:space-between"><h3>${esc(x.title)}</h3>${x.badge?`<span class="badge ${x.tone||''}">${esc(x.badge)}</span>`:''}</div><p>${esc(x.text)}</p></div></div>`).join(''):`<div class="empty-state"><h3>Nothing needs your attention.</h3><p>Agba has no active signal here.</p></div>`;}
function renderDepartments(id,items){const el=$(id);if(!el)return;el.innerHTML=items.length?items.map(d=>`<div class="dept"><div class="dept-top"><span class="dept-name">${esc(d.name)}</span><span class="health ${d.health==='warn'?'warn':d.health==='bad'?'bad':d.health==='missing'?'missing':''}"></span></div><p>${esc(d.text)}</p></div>`).join(''):`<div class="empty-state"><h3>No departments yet.</h3><p>Complete company setup to populate the operating picture.</p></div>`;}
function renderDecisions(id,items){const el=$(id);if(!el)return;el.innerHTML=items.length?items.map(d=>`<article class="decision"><time>${esc(formatDate(d.date))}</time><h3>${esc(d.title)}</h3><p>${esc(d.text)}</p></article>`).join(''):`<div class="empty-state"><h3>No leadership decisions recorded.</h3><p>Agba will keep future decisions here.</p></div>`;}
function renderActions(){const el=$('#actionsGrid');if(!el)return;const items=officeData?.actions||[];el.innerHTML=items.length?items.map(a=>`<article class="action-card"><div class="row"><div><h3>${esc(a.description)}</h3><p>${esc(a.owner_name||'Unassigned')}${a.deadline?` · Due ${esc(formatDate(a.deadline))}`:''}</p></div><span class="badge ${a.priority==='critical'?'danger':a.priority==='high'?'warn':''}">${esc(a.priority||'medium')}</span></div><div class="action-meta"><span class="badge">${esc(a.status)}</span>${a.deadline?`<span class="badge">Due ${esc(formatDate(a.deadline))}</span>`:''}</div></article>`).join(''):`<div class="empty-state"><h3>No open actions.</h3><p>Agba will track management actions here.</p></div>`;}
function renderFullDepartments(){renderDepartments('#departmentsFull',officeData?.departments||[]);}
function renderOffice(){if(!officeData)return;const m=officeData.metrics||{};const revenueEl=document.querySelector('.pulse-main .signal-row div:nth-child(1) b');const outstandingEl=document.querySelector('.pulse-main .signal-row div:nth-child(2) b');const issuesEl=document.querySelector('.pulse-main .signal-row div:nth-child(3) b');if(revenueEl)revenueEl.textContent=money(m.revenue?.value,m.revenue?.unit||'NGN');if(outstandingEl)outstandingEl.textContent=money(m.outstanding?.value,m.outstanding?.unit||'NGN');if(issuesEl)issuesEl.textContent=String((officeData.state||[]).filter(s=>s.kind==='risk'||s.kind==='issue').length);
const pulse=document.querySelector('.pulse-main .pulse-value');const pulseText=(officeData.attention||[]).length?`There ${officeData.attention.length===1?'is':'are'} ${officeData.attention.length} active signal${officeData.attention.length===1?'':'s'} Agba wants you to see today.`:'Business is stable from the evidence currently available.';if(pulse)pulse.textContent=pulseText;const pulseP=document.querySelector('.pulse-main p');if(pulseP)pulseP.textContent=`Agba connected ${officeData.reports?.length||0} recent reports, persistent state and management actions to surface what matters.`;const health=document.querySelector('.pulse-card:nth-child(2) .big-number');if(health)health.textContent=`${officeData.reporting_health||0}%`;const healthSmall=document.querySelector('.pulse-card:nth-child(2) small:last-child');if(healthSmall)healthSmall.textContent=(officeData.reporting_health||0)===100?'Every active department has reported today.':`${officeData.departments.filter(d=>d.health==='missing').length} department${officeData.departments.filter(d=>d.health==='missing').length===1?'':'s'} still need${officeData.departments.filter(d=>d.health==='missing').length===1?'s':''} a report.`;const progress=document.querySelector('.progress i');if(progress)progress.style.width=`${officeData.reporting_health||0}%`;
renderList('#attentionList',officeData.attention||[]);renderList('#changesList',officeData.changes||[]);renderDepartments('#departmentGrid',officeData.departments||[]);renderDecisions('#decisionList',officeData.decisions||[]);renderActions();renderFullDepartments();renderDecisions('#decisionsFull',officeData.decisions||[]);}
const routes={office:'/office',conversation:'/ask',actions:'/actions',departments:'/departments',decisions:'/decisions'};const titles={office:'Good morning, CEO.',conversation:'Talk to Agba.',actions:'What needs to happen.',departments:'How the business is moving.',decisions:'What leadership decided.'};
function routeForView(view){return routes[view]||'/office';}function viewForPath(path){if(path==='/ask')return'conversation';if(path==='/actions')return'actions';if(path==='/departments')return'departments';if(path==='/decisions')return'decisions';return'office';}
function go(view,{push=true}={}){$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.remove('active-view'));const el=$(`#${view}View`);if(el)el.classList.add('active-view');if($('#pageTitle'))$('#pageTitle').textContent=titles[view]||'Agba';if(push){const path=routeForView(view);if(location.pathname!==path)history.pushState({view},'',path);}window.scrollTo({top:0,behavior:'smooth'});}
function showStatus(text,connected=false){if($('#connectionText'))$('#connectionText').textContent=text;if($('#statusDot'))$('#statusDot').style.background=connected?'var(--green)':'';}
async function loadOffice(){if(!supabaseClient||!session)return;showStatus('Loading Office...');const{data,error}=await supabaseClient.functions.invoke('office-read',{body:{}});if(error)throw error;if(data?.error)throw new Error(data.error);officeData=data;organizationId=data.organization?.id||organizationId;document.title=`Agba Office · ${data.organization?.name||'Company'}`;if($('#orgName'))$('#orgName').textContent=data.organization?.name||'Live company';renderOffice();showStatus('Live company',true);}
async function askAgba(question){if(!supabaseClient||!session||!organizationId)throw new Error('Sign in required');const{data,error}=await supabaseClient.functions.invoke('ceo-query',{body:{organization_id:organizationId,question}});if(error)throw error;return data?.answer||data;}
async function sendMessage(question){const box=$('#chatMessages');box.insertAdjacentHTML('beforeend',`<div class="message user"><span class="msg-avatar">T</span><div><p>${esc(question)}</p><small>You</small></div></div>`);$('#chatInput').value='';box.insertAdjacentHTML('beforeend',`<div class="message agba" id="thinking"><span class="msg-avatar">A</span><div><p>Agba is thinking...</p><small>Reasoning from company memory</small></div></div>`);box.scrollTop=box.scrollHeight;try{const r=await askAgba(question);$('#thinking')?.remove();const actions=Array.isArray(r.actions)?r.actions:[];box.insertAdjacentHTML('beforeend',`<div class="message agba"><span class="msg-avatar">A</span><div><p>${esc(r.answer||r.response||JSON.stringify(r))}</p>${actions.length?`<small>${actions.length} action${actions.length===1?'':'s'} recorded · `:''}<small>Agba · ${esc(r.confidence||'grounded')}</small></div></div>`);await loadOffice();}catch(e){$('#thinking')?.remove();box.insertAdjacentHTML('beforeend',`<div class="message agba"><span class="msg-avatar">A</span><div><p>I could not reach the live brain right now.</p><small>Agba · ${esc(e?.message||'connection error')}</small></div></div>`);console.error(e)}box.scrollTop=box.scrollHeight;}
async function hydrateUser(){const{data,error}=await supabaseClient.from('agba_users').select('organization_id,active,full_name,agba_roles(code)').eq('auth_user_id',session.user.id).eq('active',true).maybeSingle();if(error||!data)throw new Error('Your Agba user profile could not be loaded.');organizationId=data.organization_id;const role=Array.isArray(data.agba_roles)?data.agba_roles[0]?.code:data.agba_roles?.code;if(role!=='ceo')throw new Error('The Office is currently available to CEO accounts only.');if($('#userName'))$('#userName').textContent=data.full_name||session.user.email?.split('@')[0]||'CEO';}
async function initSupabase(){if(!config.url||!config.anon){showStatus('Sign in required');return}try{supabaseClient=window.supabase.createClient(config.url,config.anon);const{data}=await supabaseClient.auth.getSession();session=data.session;if(!session){showStatus('Sign in required');return}await hydrateUser();await loadOffice();}catch(e){console.error(e);showStatus('Connection error');const pulse=document.querySelector('.pulse-main .pulse-value');if(pulse)pulse.textContent=e?.message||'Agba Office could not load the live company picture.';}}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const q=$('#chatInput').value.trim();if(q)sendMessage(q)});$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>sendMessage(b.textContent)));
$('#refreshBtn').addEventListener('click',async()=>{const b=$('#refreshBtn');b.textContent='Loading...';try{await loadOffice();b.textContent='✓ Refreshed';}catch{b.textContent='Refresh failed';}setTimeout(()=>b.textContent='↻ Refresh',1400)});
$('#reportBtn').addEventListener('click',()=>$('#reportDialog').showModal());
window.addEventListener('popstate',()=>go(viewForPath(location.pathname),{push:false}));
go(viewForPath(location.pathname),{push:false});initSupabase();