(() => {
  const esc = (v) => String(v ?? '').replace(/[&<>'\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const dateTime = (v) => { if (!v) return 'Unknown time'; const d=new Date(v); return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-NG',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}); };
  const cfg={url:window.AGBA_SUPABASE_URL||'',anon:window.AGBA_SUPABASE_ANON_KEY||''}; let client=null;
  function sb(){if(!client&&cfg.url&&cfg.anon&&window.supabase)client=window.supabase.createClient(cfg.url,cfg.anon);return client;}
  async function rpc(name,id){const s=sb();if(!s)throw Error('Agba connection is not configured');const {data:{session}}=await s.auth.getSession();if(!session)throw Error('Sign in required');const {data,error}=await s.rpc(name,{[name.includes('action')?'p_action_id':'p_decision_id']:id});if(error)throw error;return data||[];}
  function ensurePanel(){if(document.getElementById('officeHistoryPanel'))return;const el=document.createElement('div');el.id='officeHistoryPanel';el.className='history-panel';el.innerHTML='<div class="history-card"><button class="history-close" type="button">×</button><div class="eyebrow">OPERATING MEMORY</div><h2 id="historyTitle">History</h2><p id="historySubtitle"></p><div id="historyItems" class="history-items"></div></div>';document.body.appendChild(el);el.querySelector('.history-close').onclick=()=>el.classList.remove('open');}
  function style(){if(document.getElementById('office-history-style'))return;const s=document.createElement('style');s.id='office-history-style';s.textContent='.history-panel{position:fixed;inset:0;z-index:120;display:none;align-items:flex-end;justify-content:flex-end;background:rgba(0,0,0,.68);backdrop-filter:blur(4px)}.history-panel.open{display:flex}.history-card{width:min(560px,100%);height:100%;overflow:auto;background:#10161c;border-left:1px solid #303943;padding:28px;box-shadow:-20px 0 70px rgba(0,0,0,.45)}.history-close{float:right;width:34px;height:34px;border-radius:10px;border:1px solid #303943;background:#171e25;color:#c9d0ca;font-size:20px}.history-card h2{font-family:Manrope,sans-serif;font-size:25px;letter-spacing:-.04em;margin:8px 0}.history-card>p{color:#818b93;font-size:11px;line-height:1.5}.history-items{display:grid;gap:10px;margin-top:22px}.history-item{position:relative;padding:14px 15px 14px 18px;border:1px solid #29323a;background:#131a20;border-radius:12px}.history-item:before{content:"";position:absolute;left:0;top:15px;width:3px;height:26px;background:#c6f52d;border-radius:0 3px 3px 0}.history-item .op{font-size:9px;letter-spacing:.1em;font-weight:800;color:#c6f52d;text-transform:uppercase}.history-item time{display:block;font-size:9px;color:#69747d;margin-top:4px}.history-item p{font-size:10px;color:#cdd4ce;line-height:1.55;margin:8px 0 0}.history-state{margin-top:9px;font-size:9px;color:#77828a}.history-state b{color:#bfc7c0}.history-empty{padding:16px;border:1px dashed #303942;border-radius:12px;color:#78838b;font-size:10px}.history-btn{margin-top:10px;border:1px solid #303a42;background:#171e25;color:#c6f52d;border-radius:9px;padding:7px 10px;font-size:9px;font-weight:800;cursor:pointer}.action-card .history-btn{display:inline-block}@media(max-width:620px){.history-card{width:100%;height:92%;border-left:0;border-top:1px solid #303943;border-radius:20px 20px 0 0}}';document.head.appendChild(s);}
  function stateSummary(row){const after=row.after_state||{};if(row.operation==='create')return 'Created with status '+(after.status||'open')+'.';const before=row.before_state||{};const keys=['status','owner_name','deadline','priority','description'];const changes=keys.filter(k=>JSON.stringify(before[k])!==JSON.stringify(after[k])).map(k=>`${k.replace('_',' ')}: ${before[k]??'—'} → ${after[k]??'—'}`);return changes.length?changes.join(' · '):'Record updated.';}
  async function openHistory(kind,id,title){ensurePanel();const panel=document.getElementById('officeHistoryPanel'),items=document.getElementById('historyItems');document.getElementById('historyTitle').textContent=title;document.getElementById('historySubtitle').textContent=kind==='action'?'Every recorded action mutation, from creation through completion.':'Every recorded leadership decision change, including approval, rejection and supersession.';items.innerHTML='<div class="history-empty">Loading history…</div>';panel.classList.add('open');try{const rows=await rpc(kind==='action'?'agba_get_action_history':'agba_get_decision_history',id);items.innerHTML=rows.length?rows.map(r=>`<article class="history-item"><div class="op">${esc(r.operation)}</div><time>${esc(dateTime(r.created_at))}</time><p>${esc(stateSummary(r))}</p><div class="history-state">Recorded by <b>${esc(r.changed_by?'Agba user':'system')}</b></div></article>`).join(''):'<div class="history-empty">No history has been recorded for this item yet.</div>';}catch(e){items.innerHTML=`<div class="history-empty">Could not load history: ${esc(e?.message||'connection error')}</div>`;}}
  async function decisionIdForTitle(title){const s=sb();if(!s)throw Error('Agba connection is not configured');const {data:{session}}=await s.auth.getSession();if(!session)throw Error('Sign in required');const {data,error}=await s.functions.invoke('office-read',{body:{},headers:{Authorization:`Bearer ${session.access_token}`}});if(error)throw error;const row=(data?.decisions||[]).find(d=>d.title===title);return row?.id||null;}
  function wire(){document.querySelectorAll('.action-card.command-action').forEach(card=>{if(card.querySelector('.history-btn'))return;const id=card.dataset.actionId;if(!id)return;const b=document.createElement('button');b.type='button';b.className='history-btn';b.textContent='View history';b.onclick=()=>openHistory('action',id,card.querySelector('h3')?.textContent||'Action history');card.querySelector('.action-controls')?.appendChild(b);});document.querySelectorAll('#decisionsFull .decision, #decisionList .decision').forEach(card=>{if(card.querySelector('.history-btn'))return;const title=card.querySelector('strong')?.textContent||'';if(!title)return;const b=document.createElement('button');b.type='button';b.className='history-btn';b.textContent='View history';b.onclick=async()=>{try{const id=await decisionIdForTitle(title);if(id)openHistory('decision',id,title);else throw Error('Decision record not found');}catch(e){ensurePanel();document.getElementById('historyItems').innerHTML=`<div class="history-empty">${esc(e?.message||'Could not find this decision')}</div>`;document.getElementById('officeHistoryPanel').classList.add('open');}};card.appendChild(b);});}
  style(); ensurePanel(); const observer=new MutationObserver(wire);observer.observe(document.body,{childList:true,subtree:true});setTimeout(wire,600);
})();