const $=s=>document.querySelector(s);let sb=null,session=null,state=null;
const url=window.AGBA_SUPABASE_URL,anon=window.AGBA_SUPABASE_ANON_KEY;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pill=(s)=>{const v=String(s||'unknown').toLowerCase();const cls=['failed','dead','open','critical','bad','down'].includes(v)?'bad':['warn','processing','started','unknown'].includes(v)?'warn':['completed','sent','good','healthy','active'].includes(v)?'good':'';return `<span class="pill ${cls}">${esc(s||'unknown')}</span>`};
function showError(e){$('#error').innerHTML=`<div class="err">${esc(e?.message||e||'Something went wrong.')}</div>`}
async function call(body){const{data,error}=await sb.functions.invoke('superadmin-control',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
async function bootstrap(){try{$('#bootstrapBtn').disabled=true;$('#bootstrapBtn').textContent='Activating…';await call({operation:'bootstrap'});$('#error').innerHTML='<div class="notice">Platform admin access activated for this account. Reloading control plane…</div>';await load()}catch(e){showError(e)}finally{$('#bootstrapBtn').disabled=false;$('#bootstrapBtn').textContent='Activate platform admin'}}
function render(){const d=state||{};$('#components').textContent=(d.components||[]).length;$('#incidents').textContent=(d.incidents||[]).filter(x=>x.status==='open').length;$('#inboxFailed').textContent=d.telegram?.failed_inbox??0;$('#deliveryFailed').textContent=d.telegram?.failed_delivery??0;
$('#componentsTable').innerHTML=(d.components||[]).length?`<table class="table"><thead><tr><th>Component</th><th>Category</th><th>Status</th><th>Last success</th><th>Failures</th></tr></thead><tbody>${d.components.map(x=>`<tr><td><strong>${esc(x.name||x.key)}</strong><div class="mono">${esc(x.key)}</div></td><td>${esc(x.category||'—')}</td><td>${pill(x.status)}</td><td>${esc(x.last_success_at?new Date(x.last_success_at).toLocaleString():'—')}</td><td>${esc(x.failure_count||0)}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">No components are registered yet. The control plane is ready for the production component registry.</div>`;
const rows=[...(d.telegram?.inbox||[]).map(x=>({...x,type:'inbox',date:x.received_at})),...(d.telegram?.delivery||[]).map(x=>({...x,type:'delivery',date:x.created_at}))].sort((a,b)=>new Date(b.date)-new Date(a.date));
$('#queueTable').innerHTML=rows.length?`<table class="table"><thead><tr><th>Queue</th><th>Status</th><th>Attempts</th><th>Error</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.type)}</strong><div class="mono">${esc(x.id)}</div></td><td>${pill(x.status)}</td><td>${esc(x.attempts??0)} / ${esc(x.max_attempts??'—')}</td><td>${esc(x.last_error||'—')}</td><td>${['failed','dead'].includes(x.status)?`<button class="btn" data-retry="${esc(x.type)}" data-id="${esc(x.id)}">Retry</button>`:'—'}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">No Telegram queue records found.</div>`;
$('#incidentList').innerHTML=(d.incidents||[]).length?d.incidents.map(x=>`<div class="incident"><div class="row"><strong>${esc(x.title)}</strong>${pill(x.status)}</div><div class="muted">${esc(x.description||'No description')} · ${esc(x.severity)} · ${esc(x.detected_at?new Date(x.detected_at).toLocaleString():'')}</div></div>`).join(''):`<div class="empty">No incidents recorded.</div>`;
$('#recoveryTable').innerHTML=(d.recovery_actions||[]).map(x=>`<div class="incident"><div class="row"><div><strong>${esc(x.name)}</strong><div class="muted">${esc(x.description||'')}</div></div>${pill(x.risk_level)}</div></div>`).join('')||`<div class="empty">No recovery actions enabled.</div>`;
$('#auditTable').innerHTML=(d.audit||[]).length?`<table class="table"><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Actor</th></tr></thead><tbody>${d.audit.map(x=>`<tr><td>${esc(x.created_at?new Date(x.created_at).toLocaleString():'')}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type||'—')}<div class="mono">${esc(x.entity_id||'')}</div></td><td class="mono">${esc(x.actor_auth_user_id||'—')}</td></tr>`).join('')}</tbody></table>`:`<div class="empty">No superadmin activity recorded yet.</div>`;
}
function confirmRecovery(title,text,key,input){$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#modal').classList.add('open');$('#confirm').onclick=async()=>{ $('#confirm').disabled=true;try{await call({operation:'recover',key,input:{...input,confirmed:true}});$('#modal').classList.remove('open');await load();}catch(e){showError(e)}finally{$('#confirm').disabled=false}};}
async function load(){try{$('#refresh').textContent='Loading…';state=await call({operation:'overview'});render();$('#error').innerHTML='';$('#bootstrapBtn').style.display='none'}catch(e){showError(e);$('#bootstrapBtn').style.display='inline-block'}}
$('#cancel').onclick=()=>$('#modal').classList.remove('open');$('#bootstrapBtn').onclick=bootstrap;document.addEventListener('click',e=>{const b=e.target.closest('[data-retry]');if(!b)return;const type=b.dataset.retry,id=b.dataset.id;const key=type==='inbox'?'retry_telegram_inbox':'retry_telegram_delivery';confirmRecovery('Retry Telegram item',`This will put ${type} item ${id} back into the worker queue. The action will be audited.`,`${key}`,{id})});$('#refresh').onclick=load;$('#healthBtn').onclick=async()=>{try{const comps=(state?.components||[]);if(!comps.length){showError('No components are registered yet.');return}for(const c of comps)await call({operation:'recover',key:'run_component_health_check',input:{component_key:c.key,confirmed:true}});await load()}catch(e){showError(e)}};
(async()=>{try{if(!url||!anon)throw new Error('Supabase configuration missing');sb=window.supabase.createClient(url,anon);const{data}=await sb.auth.getSession();session=data.session;if(!session)throw new Error('Sign in required');await load()}catch(e){showError(e);if(session)$('#bootstrapBtn').style.display='inline-block'}})();